BEGIN TRANSACTION;
DISABLE TRIGGER TRG_UPT_TGFFIN ON TGFFIN;
DISABLE TRIGGER AD_TRG_INC_UPT_TGFFIN ON TGFFIN;
BEGIN
UPDATE TGFFIN SET DTENTSAI = '24/10/2018' WHERE NUFIN = '558840'
END;
ENABLE TRIGGER AD_TRG_INC_UPT_TGFFIN ON TGFFIN;
ENABLE TRIGGER TRG_UPT_TGFFIN ON TGFFIN;
COMMIT TRANSACTION;
