INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC)
SELECT
    PRO.CODPROD,
    EMP.CODEMP,
    0.02 as VLRDESC -- ATENÇÃO -> digite aqui o valor de desconto
FROM TGFPRO PRO
INNER JOIN TSIEMP EMP ON EMP.CODEMP not IN (200,997,997,999,998,23,25,5,40,28)
WHERE
    PRO.CODPROD > 0
	and pro.USOPROD in ('R')
	--and pro.CODPROD = 22725
AND NOT EXISTS(
        SELECT
            1
        FROM AD_DESCEMP DESCON
        WHERE
            DESCON.CODPROD = PRO.CODPROD
        AND DESCON.CODEMP = EMP.CODEMP
    )

	
	