select CODPROD, DESCRPROD,REFERENCIA, CORFUNDOCONSPRECO--, CORFONTCONSPRECO
from tgfpro
WHERE CORFUNDOCONSPRECO IS NOT NULL 
ORDER BY CODPROD
--where CODPROD in (151, 152)

--update tgfpro
--set CORFUNDOCONSPRECO = NULL
--WHERE CORFUNDOCONSPRECO IS NOT NULL 

--update tgfpro set CORFUNDOCONSPRECO = 16777062 where codprod in ()
