SELECT DISTINCT ITE.NUNOTA,ITE.CODEMP, CAB.DTNEG, CAB.CODTIPOPER
FROM TGFITE ITE INNER JOIN TGFCAB CAB ON (ITE.NUNOTA=CAB.NUNOTA)
WHERE CAB.CODTIPOPER NOT IN (920,921,909,925,998,917,923, 999)
AND ITE.ATUALESTOQUE =0 AND CAB.TIPMOV = 'V'
ORDER BY CAB.DTNEG


