SELECT DISTINCT PRO.REFERENCIA, LOC.CODLOCATA AS 'ATACADO', LOC.CODLOCAVA AS 'VAREJO', COUNT(ITE.QTDNEG) AS 'QUANTIDADE'
FROM TGFCAB_EXC CAB INNER JOIN TGFITE_EXC ITE ON (ITE.NUNOTA = CAB.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD=PRO.CODPROD)
INNER JOIN AD_LOCALEMP LOC ON (LOC.CODPROD=PRO.CODPROD AND LOC.CODEMP = ITE.CODEMP)
WHERE CAB.CODEMP= 2 --AND CAB.TIPMOV = 'D'
GROUP BY PRO.REFERENCIA, LOC.CODLOCATA, LOC.CODLOCAVA
ORDER BY PRO.REFERENCIA

