SELECT DISTINCT PAR.CODPARC,  PAR.RAZAOSOCIAL, CGC_CPF as 'CNPJ', PAR.TIPPESSOA, PAR.EMAIL, PAR.EMAILNFE
FROM TGFPAR PAR 
	--INNER JOIN TGFCAB CAB ON (CAB.CODPARC = PAR.CODPARC)
WHERE --CAB.TIPMOV = 'V'
--AND CAB.DTNEG >= '01/02/2018'
--AND CAB.CODTIPOPER = 900 AND 
PAR.ATIVO = 'S'
and CLIENTE = 'S'
