SELECT CODPROD
FROM TGFPRO
WHERE CODPROD NOT IN (SELECT DISTINCT PRO.CODPROD
FROM TGFPRO PRO INNER JOIN AD_LOCALEMP LOCA ON (LOCA.CODPROD=PRO.CODPROD)
WHERE LOCA.CODEMP = 12) AND USOPROD = 'R'--AND ATIVO ='S'
ORDER BY CODPROD


