SELECT E1.VLRVENDA, VG.NOMETAB, tab.DTVIGOR, E1.NUTAB
FROM TGFEXC E1
INNER JOIN TGFPRO PRO ON (E1.CODPROD = PRO.CODPROD)
INNER JOIN TGFTAB TAB ON (E1.NUTAB = TAB.NUTAB)
INNER JOIN VGFTAB VG ON (VG.CODTAB = TAB.CODTAB)
WHERE E1.CODPROD  = 20953 --AND E1.NUTAB = 54 
ORDER BY tab.DTVIGOR DESC --LIMIT 1
