SELECT E1.VLRVENDA, VG.NOMETAB, TAB.DTVIGOR, E1.NUTAB, PRO.CODPROD, PRO.REFERENCIA, VG.CODTAB TABELA
FROM TGFEXC E1
INNER JOIN TGFPRO PRO ON (E1.CODPROD = PRO.CODPROD)
INNER JOIN TGFTAB TAB ON (E1.NUTAB = TAB.NUTAB)
INNER JOIN VGFTAB VG ON (VG.CODTAB = TAB.CODTAB)
WHERE PRO.REFERENCIA  LIKE '201-%' 
AND VG.CODTAB IN (2,5,6)
ORDER BY PRO.REFERENCIA DESC 


SELECT REFERENCIA, CODPROD, AD_PROIBEVENDAONLINE
FROM TGFPRO
WHERE REFERENCIA LIKE '201-%'
AND AD_PROIBEVENDAONLINE IS NULL
OR REFERENCIA LIKE '202-%'
AND AD_PROIBEVENDAONLINE IS NULL
OR REFERENCIA LIKE '185-%'
AND AD_PROIBEVENDAONLINE IS NULL
OR REFERENCIA LIKE '199-%'
AND AD_PROIBEVENDAONLINE IS NULL

--UPDATE TGFPRO
--SET AD_PROIBEVENDAONLINE = 'S'
--WHERE REFERENCIA LIKE '202-%'
--AND AD_PROIBEVENDAONLINE IS NULL
--OR REFERENCIA LIKE '201-%'
--AND AD_PROIBEVENDAONLINE IS NULL
--OR REFERENCIA LIKE '185-%'
--AND AD_PROIBEVENDAONLINE IS NULL
--OR REFERENCIA LIKE '199-%'
--AND AD_PROIBEVENDAONLINE IS NULL