-- QUANTIDADE ENTREGUE ESTAVA ZERO, CANCELAMENTO DE NOTA
SELECT NUNOTA, CODPROD, QTDNEG, QTDENTREGUE,  PENDENTE FROM TGFITE WHERE NUNOTA = 204286

UPDATE TGFITE
SET QTDENTREGUE = 54
WHERE NUNOTA = 204286