-- COMPARAR AS NOTAS
SELECT NUNOTA,STATUSNFE,NUMPROTOC, CHAVENFE
FROM TGFCAB
WHERE NUNOTA IN (198823,198821)

-- UPDADTE DE APROVAÇÃO DA NOTA
--UPDATE TGFCAB
--SET STATUSNFE='A',NUMPROTOC='???'
--WHERE NUNOTA= 198821