-- SELECIONAR USUARIOS
SELECT * FROM TSIUSU
WHERE CODEMP<>1

-- BLOQUEAR USUARIOS POR DATA, SELECIONAR TODOS DIFERENTE DA EMPRESA 1
UPDATE TSIUSU
SET DTLIMACESSO= '01/01/2018'
WHERE CODEMP<>1
--WHERE CODUSU= 0