SELECT * FROM TGFNFE WHERE TGFNFE.NUNOTA = 198821
SELECT STATUSNFE, TPEMISNFE FROM TGFCAB WHERE NUNOTA = 198821


-- EMAIL COM ERRO NPE PARA ENVIAR XML PARA CLIENTE
--BEGIN TRAN
UPDATE TGFCAB SET STATUSNFE = 'I', TPEMISNFE = 1
WHERE NUNOTA = 198821
--COMMIT
--ROLLBACK