-- SELECIONAR NOTA PELO NUMERO UNICO
select NUNOTA, CODEMP, NUMNOTA, DTNEG, VLRNOTA,CODPARCTRANSP
from tgfcab
where nunota = 131329
-- INSERIR PARCEIRO NA NOTA
UPDATE TGFCAB
SET CODPARCTRANSP= 11047
WHERE NUNOTA= 131329