
SELECT *
FROM TGFFIN FIN
INNER JOIN TSIUSU US ON (US.CODUSU=FIN.CODUSU)
WHERE FIN.DTVENCINIC BETWEEN ('01/03/2018') AND ('30/03/2018')
AND FIN.CODEMP=1
AND FIN.CODTIPTIT=44
AND FIN.CODCTABCOINT=24
AND FIN.DHBAIXA IS NULL
--AND FIN.CODUSU=133

