-- SELECIONAR NOTA PELO NUMERO UNICO
select STATUSNFE, NUMNOTA, NUNOTA
from TGFCAB
where nunota = 208209

-- INSERIR PARCEIRO NA NOTA
UPDATE TGFCAB
SET STATUSNFE= 'E'
WHERE NUNOTA= 208209
AND NUMNOTA=196017