WITH X AS (
SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 ,SUM(CAB.VLRNOTA) AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -6, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,-5,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , SUM(CAB.VLRNOTA) AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -5, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,-4,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , SUM(CAB.VLRNOTA) AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -4, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,-3,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , SUM(CAB.VLRNOTA) AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,-2,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , SUM(CAB.VLRNOTA) AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -2, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,-1,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , SUM(CAB.VLRNOTA) AS 'VALOR5'
	 , 0.00 AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(MONTH,0,DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)))
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

UNION ALL

SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO AS 'VENDEDOR', ISNULL(G.CODGRUPO,0) AS CODGRUPO
	 , G.NOME
	 , 0.00 AS 'VALOR'
	 , 0.00 AS 'VALOR1'
	 , 0.00 AS 'VALOR2'
	 , 0.00 AS 'VALOR3'
	 , 0.00 AS 'VALOR4'
	 , 0.00 AS 'VALOR5'
	 , SUM(CAB.VLRNOTA) AS 'VALOR6'
	 
FROM TGFPAR PAR 
	LEFT JOIN TGFVEN VEN ON (PAR.CODVEND=VEN.CODVEND)
	LEFT JOIN TGFCAB CAB ON (CAB.CODPARC=PAR.CODPARC 
			AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(MONTH, -0, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND GETDATE()
			--AND CAB.DTNEG BETWEEN '01/03/2019' AND '31/03/2019' 
			AND CAB.TIPMOV = 'V'
			AND CAB.CODEMP = :CODEMP)
	LEFT JOIN AD_GRUPOSPARCEIROS G ON PAR.AD_CODGRUPO = G.CODGRUPO
WHERE PAR.CODVEND = :CODVEN
AND PAR.CLIENTE = 'S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO, G.CODGRUPO, G.NOME

) --Select * from X

SELECT TOP 100
       CODGRUPO
	 , NOME
	 , VENDEDOR
	 , format(ROUND(CONVERT(MONEY,VALOR),2),'##,##0.00') AS 'VALOR'
	 , format(ROUND(CONVERT(MONEY,VALOR1),2),'##,##0.00') AS 'VALOR1'
	 , format(ROUND(CONVERT(MONEY,VALOR2),2),'##,##0.00') AS 'VALOR2'
	 , format(ROUND(CONVERT(MONEY,VALOR3),2),'##,##0.00') AS 'VALOR3'
	 , format(ROUND(CONVERT(MONEY,VALOR4),2),'##,##0.00') AS 'VALOR4'
	 , format(ROUND(CONVERT(MONEY,VALOR5),2),'##,##0.00') AS 'VALOR5'
     , format(ROUND(CONVERT(MONEY,VALOR6),2),'##,##0.00') AS 'VALOR6'
  FROM (SELECT CODGRUPO
			 , '(G) '+NOME AS NOME
			 , VENDEDOR AS 'VENDEDOR'
			 , SUM(VALOR) AS 'VALOR'
			 , SUM(VALOR1) AS 'VALOR1'
			 , SUM(VALOR2) AS 'VALOR2'
			 , SUM(VALOR3) AS 'VALOR3'
			 , SUM(VALOR4) AS 'VALOR4'
			 , SUM(VALOR5) AS 'VALOR5'
			 , SUM(VALOR6) AS 'VALOR6'
		  FROM X
		 WHERE CODGRUPO > 0
		   AND :TIPO = 'G'
		 GROUP BY CODGRUPO
				, NOME
				, VENDEDOR
		 UNION ALL
		SELECT CODPARC
			 , RAZAOSOCIAL
			 , VENDEDOR AS 'VENDEDOR'
			 , SUM(VALOR) AS 'VALOR'
			 , SUM(VALOR1) AS 'VALOR1'
			 , SUM(VALOR2) AS 'VALOR2'
			 , SUM(VALOR3) AS 'VALOR3'
			 , SUM(VALOR4) AS 'VALOR4'
			 , SUM(VALOR5) AS 'VALOR5'
			 , SUM(VALOR6) AS 'VALOR6'

		  FROM X
		 WHERE ((CODGRUPO = 0
		   AND :TIPO = 'G')
		    OR (:TIPO <> 'G'))
		 GROUP BY CODPARC
				, RAZAOSOCIAL
				, VENDEDOR) Z
