SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, REG.NOMEREG, PAR.TELEFONE, PAR.AD_CODPARCREAL--, CAB.DTNEG
FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (CAB.CODEMP=EMP.CODEMP)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TSIREG REG ON (PAR.CODREG=REG.CODREG)
WHERE CAB.TIPMOV='V'AND
PAR.BLOQUEAR = 'N' AND
PAR.CLIENTE = 'S'  AND
PAR.TIPPESSOA = 'J' AND
CAB.CODEMP = 11 AND
REG.NOMEREG LIKE  '%ESPIRI%' AND 
PAR.MOTBLOQ IS NULL AND 
CAB.CODPARC NOT IN (
	SELECT CODPARC FROM TGFCAB WHERE DTNEG BETWEEN DATEADD(month, -1, GETDATE()) AND GETDATE())
GROUP BY PAR.CODPARC, PAR.TELEFONE, PAR.RAZAOSOCIAL, PAR.AD_CODPARCREAL, REG.NOMEREG--, CAB.DTNEG
--ORDER BY CAB.DTNEG DESC 

--SELECT NOMEPARC FROM TGFPAR WHERE CLIENTE='S' AND ATIVO='S' AND CODPARC NOT IN (
--	SELECT CODPARC FROM TGFCAB WHERE DTNEG BETWEEN DATEADD(month, -1, GETDATE()) AND GETDATE()
--)

