SELECT FIN.CODPARC
     , PAR.RAZAOSOCIAL
     , FIN.DTVENC
	 , FIN.DTNEG
	 , FIN.VLRDESDOB
	 , ROUND(FIN.VLRDESDOB + FIN.VLRDESDOB*([sankhya].[GET_TSIPAR_NUMERO]('PERCMULTA')/100)
	 + FIN.VLRDESDOB*(([sankhya].[GET_TSIPAR_NUMERO]('TAXADIAATRASO')/100)*DATEDIFF(DAY,FIN.DTVENC,GETDATE())),2) AS VLRATUALIZADO
	 , DATEDIFF(DAY,FIN.DTVENC,GETDATE()) AS DIAS_ATRASO
	 , FIN.NUFIN
  FROM TGFFIN FIN INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
                  INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
 WHERE FIN.DTVENC <= DATEADD(DAY,:DIAS*-1,CONVERT(DATE,GETDATE()))
   AND FIN.DHBAIXA IS NULL
   AND FIN.RECDESP = 1
   AND (
		(USU.CODEMP IS NULL AND FIN.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND FIN.CODEMP = USU.CODEMP)
	)
--   AND DATEDIFF(YEAR,FIN.DTVENC,GETDATE()) < 5
   AND FIN.CODTIPTIT NOT IN (69)
   AND FIN.CODPARC = ISNULL(:CODPARC,FIN.CODPARC)
   AND ((CONVERT(DATE,FIN.DTVENC) BETWEEN :PERIODO.INI AND :PERIODO.FIN AND :PERIODO.INI IS NOT NULL AND :PERIODO.FIN IS NOT NULL)
    OR (:PERIODO.INI IS NULL))