SELECT TAB.NUTAB,VG.NOMETAB,
PRO.REFERENCIA, tab.DTVIGOR AS DATA_ANTERIOR , E1.VLRVENDA AS 'VALOR_ANTERIOR', 

E2.VLRVENDA AS 'VALOR_ATUAL', tab2.DTVIGOR AS DATA_ATUAL,
(E1.VLRVENDA-E2.VLRVENDA) AS 'DIFERENÇA'
--,TAB2.NUTAB,VG2.NOMETAB,PRO2.REFERENCIA, tab2.DTVIGOR AS DATA_ALTERACAO
FROM TGFEXC E1
INNER JOIN TGFPRO PRO ON (E1.CODPROD = PRO.CODPROD)
INNER JOIN TGFTAB TAB ON (E1.NUTAB = TAB.NUTAB)
INNER JOIN VGFTAB VG ON (VG.CODTAB = TAB.CODTAB),
TGFEXC E2
INNER JOIN TGFPRO PRO2 ON (E2.CODPROD = PRO2.CODPROD)
INNER JOIN TGFTAB TAB2 ON (E2.NUTAB = TAB2.NUTAB)
INNER JOIN VGFTAB VG2 ON (VG2.CODTAB = TAB2.CODTAB)

WHERE VG.NOMETAB like 'TABELA PREÇO PAULISTA' 
AND tab.DTVIGOR = '16/07/2020' --BETWEEN '02/07/2020' and '02/07/2020'
AND E1.CODPROD = E2.CODPROD
AND VG2.NOMETAB like 'TABELA PREÇO PAULISTA' 
AND tab2.DTVIGOR = '23/07/2020' --BETWEEN '02/07/2020' and '02/07/2020'
AND (E1.VLRVENDA-E2.VLRVENDA) <> 0

ORDER BY DIFERENÇA DESC

