select x.NUNOTA AS NUMERO_UNICO,c.NUMNOTA,c.DTNEG,
SUBSTRING(x.XML,CHARINDEX('<xNome>',x.XML)+7,(CHARINDEX('</xNome>',x.XML)-CHARINDEX('<xNome>',x.XML)-7)) EMPRESA,
E.RAZAOSOCIAL
from TGFNFE x
inner join TGFCAB c ON (c.NUNOTA=x.NUNOTA)
inner join TSIEMP E ON (E.CODEMP = C.CODEMP)
where SUBSTRING(x.XML,CHARINDEX('<xNome>',x.XML)+7,6) <> 'REAL O' and x.NUNOTA>123933 AND C.CODEMP=12 order by EMPRESA,x.NUNOTA desc

