SELECT DISTINCT
  CTE.CODPROD             AS "CódProd",
  PRO.REFERENCIA          AS "REFERENCIA",
  CTE.CONTROLE            AS "Controle_Adicional",
  CTE.CODVOL              AS "CódVol",
  CTE.DTCONTAGEM          AS "Dt_Contagem_1",
  CTE.QTDEST              AS "Qtd_Contagem_1",
  CT2.DTCONTAGEM          AS "Dt_Contagem_2",
  SUM(CASE WHEN CT2.QTDEST IS NULL THEN 0 ELSE CT2.QTDEST END)  AS "Qtd_Contagem_2",
  LOC.CODLOCAL            AS "Cód_Local",
  LOC.DESCRLOCAL          AS "Desc_Local",
  CASE WHEN count(CTE.SEQUENCIA) > 1 THEN  SUM(CT2.QTDEST) - CTE.QTDEST ELSE SUM(CASE WHEN CT2.QTDEST IS NULL AND CT2.QTDEST = CTE.QTDEST THEN 0 WHEN CT2.QTDEST < CTE.QTDEST THEN CT2.QTDEST - CTE.QTDEST ELSE CT2.QTDEST -CTE.QTDEST END) END AS "QtdDif",
  CTE.SEQUENCIA,
  CT2.SEQUENCIA
FROM
  TGFCTE CTE,
  TGFCTE CT2,
  TGFLOC LOC,
  TGFPRO PRO
WHERE
  CTE.CODPROD    = CT2.CODPROD
AND CTE.CODPROD  = PRO.CODPROD
AND CTE.CODLOCAL = CT2.CODLOCAL
AND CTE.TIPO     = CT2.TIPO
AND CTE.CONTROLE = CT2.CONTROLE
AND CTE.CODPARC  = CT2.CODPARC
AND CTE.CODEMP   = CT2.CODEMP
AND CTE.CODLOCAL =LOC.CODLOCAL
AND
  ( ( CT2.QTDEST - CTE.QTDEST <> 0)
  AND ( CTE.DTCONTAGEM = '03/10/2018' AND CTE.SEQUENCIA = 1)
  AND ( CT2.DTCONTAGEM = '03/10/2018' AND CT2.SEQUENCIA > 1 )
  )
GROUP BY
  CTE.CODPROD,
  PRO.REFERENCIA,
  CTE.CONTROLE,
  CTE.CODVOL,
  CTE.DTCONTAGEM,
  CT2.DTCONTAGEM,
  LOC.CODLOCAL,
  LOC.DESCRLOCAL,
  --CT2.QTDEST, 
  CTE.QTDEST,
  CTE.SEQUENCIA,
  CT2.SEQUENCIA
ORDER BY
  "Cód_Local",
  "CódProd",
  "Controle_Adicional"

  --select * from TGFCTE where DTCONTAGEM = '03/10/2018' and QTDEST <>0 and codprod = 26094