SELECT 
C.CODEMP LOJA,
P.CODPARC AS CODIGO_PARCEIRO,
LTRIM(RTRIM(P.NOMEPARC)) PARCEIRO,

--VALOR TOTAL DA VENDA NO PERIODO
(SELECT SUM(CAB.VLRNOTA)
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND P.CODPARC = CAB.CODPARC
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
) VALOR_PERIODO,

--VALOR GERAL POR EMPRESA NO PERIODO
(SELECT (SUM(CAB.VLRNOTA))
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
	--AND CAB.DTNEG BETWEEN '01/01/2018' AND '31/01/2018'
) VALOR_GERAL,

-- QUANTIDADE DE VENDAS NOS ULTIMOS 30 DIAS
(SELECT COUNT(CAB.NUNOTA)
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND P.CODPARC = CAB.CODPARC
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
) QUANT_VENDAS,

-- MEDIAS DE VENDAS POR PARCEIRO NOS ULTIMOS 30 DIAS
(SELECT (AVG(CAB.VLRNOTA))	
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND P.CODPARC = CAB.CODPARC
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
) MEDIA_VENDAS,

-- MEDIAS DE VENDAS POR PARCEIRO NOS ULTIMOS 30 DIAS
(SELECT (AVG(CAB.VLRNOTA))	
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
) MEDIA_VENDAS_GERAL,

-- CALCULO DE PORCENTAGEM POR PARCEIRO NOS ULTIMOS 30 DIAS
(SELECT (((SELECT AVG(CAB1.VLRNOTA)	
	FROM TGFCAB CAB1
	WHERE CAB1.TIPMOV='V'
	AND CAB1.STATUSNFE = 'A'
	AND E.CODEMP=CAB1.CODEMP
	AND P.CODPARC = CAB1.CODPARC
	AND DATEPART(MONTH, CAB1.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB1.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB1.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
)*0.01  / SUM(CAB.VLRNOTA)))
	FROM TGFCAB CAB
	WHERE CAB.TIPMOV='V'
	AND CAB.STATUSNFE = 'A'
	AND E.CODEMP=CAB.CODEMP
	AND DATEPART(MONTH, CAB.DTNEG) = DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
    AND DATEPART(YEAR, CAB.DTNEG) = DATEPART(YEAR, DATEADD(MONTH, -1, GETDATE()))
	--AND CAB.DTNEG BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
) P_VENDAS

-- CALCULO DE PORCENTAGEM POR PARCEIRO NOS ULTIMOS 30 DIAS

	
FROM TGFCAB C
INNER JOIN TSIEMP E ON (E.CODEMP=C.CODEMP)
INNER JOIN TGFPAR P ON (P.CODPARC=C.CODPARC)

WHERE C.TIPMOV='V'
AND C.STATUSNFE = 'A'
-- AND E.CODEMP=1
GROUP BY C.CODEMP, P.NOMEPARC, P.CODPARC, C.CODPARC,P.CODEMP, E.CODEMP
ORDER BY VALOR_PERIODO DESC