SELECT

	LOJA,
	COD_PRODUTO,
	REFERENCIA,
	PRODUTO,
	TOTAL_VENDA_PRODUTO_M AS MEDIA,
	TOTAL_VENDA_PRODUTO_AC AS ACUMULADO,
	TOTAL_VENDA_PRODUTO_C3 AS C3,
	TOTAL_VENDA_PRODUTO_C2 AS C2,
	TOTAL_VENDA_PRODUTO_C1 AS C1,
 TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PRODUTO_AC DESC) 'PORC_AC'

FROM (

SELECT TOP 50
CAB.CODEMP LOJA,
PPR.REFERENCIA REFERENCIA,
ITE.CODPROD COD_PRODUTO,
LTRIM(RTRIM(PPR.DESCRPROD)) PRODUTO,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
) TOTAL_VENDA_GERAL_AC,

(SELECT
SUM(I.VLRTOT)/3 VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
) TOTAL_VENDA_PRODUTO_M,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
) TOTAL_VENDA_PRODUTO_AC,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE()))
) TOTAL_VENDA_PRODUTO_C3,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))
) TOTAL_VENDA_PRODUTO_C2,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
) TOTAL_VENDA_PRODUTO_C1

FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PPR ON (PPR.CODPROD=ITE.CODPROD)

WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND EMP.CODEMP = :CODEMP

AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)

GROUP BY CAB.CODEMP, PPR.DESCRPROD, PPR.CODPROD, CAB.CODEMP,ITE.CODPROD,PPR.REFERENCIA
ORDER BY TOTAL_VENDA_PRODUTO_AC DESC

) SUB