SELECT /* INFORME FUNCIONARIOS*/ * 
  FROM (
SELECT *
    FROM (

(SELECT /*CURVA ABC - VALOR NO PERIODO -1 PARCEIRO*/

	LOJA,
	COD_PARCEIRO,
	PARCEIRO,
	TOTAL_VENDA_PARCEIRO_AC AS 'VALOR',
 TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC) 'PORC_AC',
	CASE WHEN :TIPO = 'A' THEN 'PERIDO - 1' WHEN :TIPO = 'B' THEN 'PERIDO - 2' WHEN :TIPO = 'C' THEN 'PERIDO - 3' END AS 'PERIODOS'

FROM (

SELECT TOP 100
:CODEMP LOJA,
PAR.CODPARC COD_PARCEIRO,
LTRIM(RTRIM(PAR.NOMEPARC)) PARCEIRO,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -1, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -0, GETDATE()))
) TOTAL_VENDA_GERAL_AC,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC= PAR.CODPARC
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -1, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -0, GETDATE()))
 ) TOTAL_VENDA_PARCEIRO_AC

FROM TGFPAR PAR 
WHERE EXISTS (SELECT 1 FROM TGFCAB CAB 
               WHERE CAB.TIPMOV='V' 
			     AND CAB.STATUSNFE = 'A' 
			     AND CAB.CODEMP = :CODEMP
				 AND CAB.CODTIPOPER IN (900,901)
                  AND CAB.CODVEND <> 59 
			     AND EXISTS (SELECT 1 FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69 AND NUNOTA = CAB.NUNOTA))
AND :TIPO = 'A'
GROUP BY PAR.NOMEPARC, PAR.CODPARC, PAR.CODPARC, PAR.CODEMP
ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC

) SUB

)

UNION ALL

(SELECT /*CURVA ABC - VALOR NO PERIODO -2 PARCEIRO*/

	LOJA,
	COD_PARCEIRO,
	PARCEIRO,
	TOTAL_VENDA_PARCEIRO_AC AS 'VALOR',
 TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC) 'PORC_AC',
	CASE WHEN :TIPO = 'A' THEN 'PERIDO - 1' WHEN :TIPO = 'B' THEN 'PERIDO - 2' WHEN :TIPO = 'C' THEN 'PERIDO - 3' END AS 'PERIODOS'

FROM (

SELECT TOP 100
:CODEMP LOJA,
PAR.CODPARC COD_PARCEIRO,
LTRIM(RTRIM(PAR.NOMEPARC)) PARCEIRO,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -2, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
) TOTAL_VENDA_GERAL_AC,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC= PAR.CODPARC
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -2, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
 ) TOTAL_VENDA_PARCEIRO_AC

FROM TGFPAR PAR 
WHERE EXISTS (SELECT 1 FROM TGFCAB CAB 
               WHERE CAB.TIPMOV='V' 
			     AND CAB.STATUSNFE = 'A' 
			     AND CAB.CODEMP = :CODEMP
				 AND CAB.CODTIPOPER IN (900,901)
                  AND CAB.CODVEND <> 59 
			     AND EXISTS (SELECT 1 FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69 AND NUNOTA = CAB.NUNOTA))
AND :TIPO = 'B'
GROUP BY PAR.NOMEPARC, PAR.CODPARC, PAR.CODPARC, PAR.CODEMP
ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC

) SUB

)

UNION ALL

(SELECT /*CURVA ABC - VALOR NO PERIODO -3 PARCEIRO*/

	LOJA,
	COD_PARCEIRO,
	PARCEIRO,
	TOTAL_VENDA_PARCEIRO_AC AS 'VALOR',
 TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC) 'PORC_AC',
	CASE WHEN :TIPO = 'A' THEN 'PERIDO - 1' WHEN :TIPO = 'B' THEN 'PERIDO - 2' WHEN :TIPO = 'C' THEN 'PERIDO - 3' END AS 'PERIODOS'

FROM (

SELECT TOP 100
:CODEMP LOJA,
PAR.CODPARC COD_PARCEIRO,
LTRIM(RTRIM(PAR.NOMEPARC)) PARCEIRO,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -3, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -2, GETDATE()))
) TOTAL_VENDA_GERAL_AC,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC= PAR.CODPARC
AND C.CODEMP = :CODEMP
AND C.CODTIPOPER IN (900,901)
AND C.DTNEG BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -3, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -2, GETDATE()))
 ) TOTAL_VENDA_PARCEIRO_AC

FROM TGFPAR PAR 
WHERE EXISTS (SELECT 1 FROM TGFCAB CAB 
               WHERE CAB.TIPMOV='V' 
			     AND CAB.STATUSNFE = 'A' 
			     AND CAB.CODEMP = :CODEMP
                 AND CAB.CODTIPOPER IN (900,901)
                 AND CAB.CODVEND <> 59 
			     AND EXISTS (SELECT 1 FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69 AND NUNOTA = CAB.NUNOTA))
AND :TIPO = 'C'
GROUP BY PAR.NOMEPARC, PAR.CODPARC, PAR.CODPARC, PAR.CODEMP
ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC

) SUB

)


) SUB) X