SELECT

	LOJA,
	COD_PARCEIRO,
	PARCEIRO,
	TOTAL_VENDA_PARCEIRO_M AS MEDIA,
	TOTAL_VENDA_PARCEIRO_AC AS ACUMULADO,
	TOTAL_VENDA_PARCEIRO_C3 AS C3,
	TOTAL_VENDA_PARCEIRO_C2 AS C2,
	TOTAL_VENDA_PARCEIRO_C1 AS C1,
 TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PARCEIRO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC) 'PORC_AC'

FROM (

SELECT TOP 100
CAB.CODEMP LOJA,
CAB.CODPARC COD_PARCEIRO,
LTRIM(RTRIM(PAR.NOMEPARC)) PARCEIRO,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_GERAL_AC,

(SELECT
SUM(I.VLRTOT)/3 VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC=CAB.CODPARC
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_PARCEIRO_M,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC=CAB.CODPARC
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_PARCEIRO_AC,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC=CAB.CODPARC
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_PARCEIRO_C3,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC=CAB.CODPARC
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_PARCEIRO_C2,

(SELECT
SUM(I.VLRTOT) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODPARC=CAB.CODPARC
AND C.CODEMP=CAB.CODEMP
AND DATEPART(MONTH, C.DTNEG) BETWEEN DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE())) AND DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))
--AND ((CONVERT(DATE,C.DTNEG) BETWEEN DATEADD(MONTH, -3, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND DATEADD(DAY, -1, DateAdd(mm, DateDiff(mm,0,GETDATE()) - 0, 0)) AND :PERIODO.INI IS NULL))
) TOTAL_VENDA_PARCEIRO_C1

FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)

WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND EMP.CODEMP = :CODEMP

AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)

GROUP BY CAB.CODEMP, PAR.NOMEPARC, PAR.CODPARC, CAB.CODPARC,PAR.CODEMP, EMP.CODEMP
ORDER BY TOTAL_VENDA_PARCEIRO_AC DESC

) SUB