SELECT * 
     , DATEDIFF(DAY,:PERIODO.INI,:PERIODO.FIN) AS DIAS
     , QTD/DATEDIFF(DAY,:PERIODO.INI,:PERIODO.FIN) AS MEDIA
     , ESTOQUE/(QTD/DATEDIFF(DAY,:PERIODO.INI,:PERIODO.FIN)) AS VIDA_ESTOQUE
  FROM (
SELECT /*CURVA ABC - ACUMULADO PRODUTO QTD*/
    RANK() OVER (ORDER BY TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC DESC) AS RANK,
	LOJA,
	COD_PRODUTO,
	REFERENCIA,
	PRODUTO,
	TOTAL_VENDA_PRODUTO_AC AS ACUMULADO,
    TOTAL_VENDA_GERAL_AC AS VALOR_TOTAL,
	TOTAL_VENDA_PRODUTO_AC1 AS QUANTIDADE,
	TOTAL_VENDA_PRODUTO_QTD AS QTD, 
	TOTAL_COMPRA_PRODUTO_AC AS COMPRAS,
	TOTAL_COMPRA_PRODUTO_AC - TOTAL_VENDA_PRODUTO_AC1 AS SALDO,
	(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) AS 'PORC',
	SUM(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PRODUTO_AC DESC) 'PORC_AC',
	100-SUM(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PRODUTO_AC DESC) PORC_DESC,
    CASE WHEN 100-SUM(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PRODUTO_AC DESC) > [sankhya].[GET_TSIPAR_NUMERO] ('LIMCURVA_BPRO') THEN 'A'
	     WHEN 100-SUM(TOTAL_VENDA_PRODUTO_AC*100/TOTAL_VENDA_GERAL_AC) OVER (PARTITION BY LOJA ORDER BY TOTAL_VENDA_PRODUTO_AC DESC) BETWEEN [sankhya].[GET_TSIPAR_NUMERO] ('LIMCURVA_CPRO')+0.01 AND [sankhya].[GET_TSIPAR_NUMERO] ('LIMCURVA_BPRO') THEN 'B'
		 ELSE 'C' END AS CURVA,
	[sankhya].[GET_TSIPAR_NUMERO] ('LIMCURVA_BPRO') AS LIMITEB,
	[sankhya].[GET_TSIPAR_NUMERO] ('LIMCURVA_CPRO') AS LIMITEC,
  (SELECT SUM(ESTOQUE) FROM TGFEST WHERE CODPROD = COD_PRODUTO AND CODEMP = LOJA AND CODPARC = 0) ESTOQUE

FROM (

SELECT TOP 100 PERCENT
CAB.CODEMP LOJA,
PPR.REFERENCIA REFERENCIA,
ITE.CODPROD COD_PRODUTO,
LTRIM(RTRIM(PPR.DESCRPROD)) PRODUTO,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_GERAL_AC,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_AC1,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_QTD,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_AC,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.CODTIPOPER IN (701,712)
AND C.STATUSNOTA = 'L'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTENTSAI) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_COMPRA_PRODUTO_AC

FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PPR ON (PPR.CODPROD=ITE.CODPROD)

WHERE CAB.CODTIPOPER IN (900,901,931)
  AND CAB.STATUSNOTA = 'L'
  AND EMP.CODEMP = :CODEMP

AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
AND :TIPO = 'Q'
GROUP BY CAB.CODEMP, PPR.DESCRPROD, PPR.CODPROD, CAB.CODEMP,ITE.CODPROD,PPR.REFERENCIA
UNION ALL
SELECT TOP 100 PERCENT
CAB.CODEMP LOJA,
PPR.REFERENCIA REFERENCIA,
ITE.CODPROD COD_PRODUTO,
LTRIM(RTRIM(PPR.DESCRPROD)) PRODUTO,

ISNULL((SELECT
SUM(I.VLRUNIT*I.QTDNEG-I.VLRDESC) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND C.CODEMP = CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_GERAL_AC,

ISNULL((SELECT
SUM(I.VLRUNIT*I.QTDNEG-I.VLRDESC) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_AC1,

ISNULL((SELECT
SUM(I.QTDNEG) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_QTD,

ISNULL((SELECT
SUM(I.VLRUNIT*I.QTDNEG-I.VLRDESC) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.TIPMOV='V' AND C.STATUSNFE = 'A'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTNEG) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_VENDA_PRODUTO_AC,

ISNULL((SELECT
SUM(I.VLRUNIT*I.QTDNEG-I.VLRDESC) VLRTOT
FROM TGFITE I
INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA)
WHERE C.CODTIPOPER IN (701,712)
AND C.STATUSNOTA = 'L'
AND I.CODPROD=ITE.CODPROD
AND C.CODEMP=CAB.CODEMP
AND ((CONVERT(DATE,C.DTENTSAI) BETWEEN :PERIODO.INI AND :PERIODO.FIN))
),0) TOTAL_COMPRA_PRODUTO_AC

FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PPR ON (PPR.CODPROD=ITE.CODPROD)

WHERE CAB.CODTIPOPER IN (900,901,931)
  AND CAB.STATUSNOTA = 'L'
  AND EMP.CODEMP = :CODEMP

AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
AND :TIPO = 'V'
GROUP BY CAB.CODEMP, PPR.DESCRPROD, PPR.CODPROD, CAB.CODEMP,ITE.CODPROD,PPR.REFERENCIA
ORDER BY TOTAL_VENDA_PRODUTO_AC DESC

) SUB
WHERE TOTAL_VENDA_PRODUTO_AC1 > 0) X
WHERE (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND REFERENCIA LIKE :GRUPO+'%')
  ))
ORDER BY 14 DESC