SELECT /*CURVA ABC - PRODUTO QUANTIDADE SAIDA*/
DISTINCT
	PRODUTO,
	DESCRICAO,
	CASE WHEN T2 <> T1 THEN ((T1*100/T2)-100) ELSE  0 END  AS 'DIFERENÇA',
	T1 AS 'ATUAL',
	T2 AS 'ANTERIOR'

FROM (

SELECT TOP 2
CAB.DTENTSAI AS 'DATA_ENTRADA',
PRO.REFERENCIA AS 'PRODUTO',
PRO.DESCRPROD AS 'DESCRICAO',


	(SELECT V_UNIT
	FROM (
		SELECT row_number() OVER (ORDER BY DATA_ENTRADA DESC) AS row_number, *
		FROM (
			SELECT
				CAB.DTENTSAI AS 'DATA_ENTRADA',
				ITE.VLRUNIT AS 'V_UNIT'			

			FROM TGFCAB CAB
			INNER JOIN TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
			INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
			INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)

			WHERE CAB.TIPMOV = 'C'
			AND CAB.STATUSNOTA = 'L'
			AND CAB.CODEMP = 2
			AND (
				(LEN('202-8110176BR') > 4 AND PRO.REFERENCIA LIKE '202-8110176BR') OR
				(LEN('202-8110176BR') <= 4 AND PRO.REFERENCIA LIKE '202-8110176BR'+'%')
			)

		) SUB
	) TabelaNumerada
	WHERE row_number BETWEEN 0 AND 1) T1,

	(SELECT V_UNIT
	FROM (
		SELECT row_number() OVER (ORDER BY DATA_ENTRADA DESC) AS row_number, *
		FROM (
			SELECT
				CAB.DTENTSAI AS 'DATA_ENTRADA',
				ITE.VLRUNIT AS 'V_UNIT'			

			FROM TGFCAB CAB
			INNER JOIN TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
			INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
			INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)

			WHERE CAB.TIPMOV = 'C'
			AND CAB.STATUSNOTA = 'L'
			AND CAB.CODEMP = 2
			AND (
				(LEN('202-8110176BR') > 4 AND PRO.REFERENCIA LIKE '202-8110176BR') OR
				(LEN('202-8110176BR') <= 4 AND PRO.REFERENCIA LIKE '202-8110176BR'+'%')
			)
		) SUB
	) TabelaNumerada
	WHERE row_number BETWEEN 2 AND 2) T2


FROM TGFCAB CAB
	INNER JOIN TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
	INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
	INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)

	WHERE CAB.TIPMOV = 'C'
	AND CAB.STATUSNOTA = 'L'
	AND CAB.CODEMP = 2
	AND (
		(LEN('202-8110176BR') > 4 AND PRO.REFERENCIA LIKE '202-8110176BR') OR
		(LEN('202-8110176BR') <= 4 AND PRO.REFERENCIA LIKE '202-8110176BR'+'%')
	)

) SUB