SELECT DISTINCT
--ROW_NUMBER() OVER (ORDER BY CAB.NUNOTA) ITEM,
PRO.CODPROD,
PRO.REFERENCIA AS NOSSO_CODIGO,
PAP.CODPROPARC AS FORNECEDOR_CODIGO,
PAR.RAZAOSOCIAL,
--(CASE
--    WHEN VOA.CODPROD IS NULL THEN ITE.QTDNEG
--	WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN ITE.QTDNEG * VOA.QUANTIDADE
--	ELSE ITE.QTDNEG / VOA.QUANTIDADE
--END) AS QUANTIDADE,
--ITE.CODVOL,
PRO.DESCRPROD,
PRO.REFFORN AS REFERENCIA_FORNECEDOR
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPAP PAP ON PAP.CODPROD = PRO.CODPROD AND PAP.CODPARC = CAB.CODPARC AND (PAP.CODEMP = CAB.CODEMP OR (PAP.CODEMP IS NULL AND PAP.SEQUENCIA=0))
LEFT JOIN TGFPAR PAR ON PAP.CODPARC = PAR.CODPARC
LEFT JOIN TGFVOA VOA ON(VOA.CODPROD = ITE.CODPROD AND VOA.CODVOL = ITE.CODVOL AND ((ITE.CONTROLE IS NULL AND VOA.CONTROLE = ' ') OR (ITE.CONTROLE IS NOT NULL AND ITE.CONTROLE = VOA.CONTROLE)))
WHERE
--ITE.NUNOTA = ISNULL--($P{NUNOTA},$P{PK_NUNOTA}) 
--AND
ITE.SEQUENCIA > 0
AND PRO.USOPROD = 'R'
AND CAB.TIPMOV = 'C'
--AND PRO.REFFORN IS NULL 
ORDER BY PRO.CODPROD