SELECT  DISTINCT PRO.CODPROD, PRO.REFERENCIA, PRO.DESCRPROD, PAR.CODPARC, PAR.RAZAOSOCIAL
FROM TGFCAB C   INNER JOIN TGFITE ITE ON C.NUNOTA = ITE.NUNOTA
				  INNER JOIN TGFPRO PRO ON (ITE.CODPROD=PRO.CODPROD)
				  INNER JOIN TGFPAR PAR ON (PAR.CODPARC=C.CODPARC)
WHERE C.TIPMOV = 'C'
	  AND PRO.USOPROD='R'
	  AND PAR.ATIVO = 'S'
	  AND PRO.ATIVO = 'S'
   AND (PAR.CODPARC = :PARCEIRO OR :PARCEIRO IS NULL)
	  AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
))
	  AND C.CODPARC NOT IN (6060,6055,6057,6064,6065,6056,6063,6061,6058,8570,6062)
	  AND C.DTENTSAI = (SELECT MAX(CAB.DTENTSAI) FROM TGFCAB CAB INNER JOIN TGFITE I ON (CAB.NUNOTA=I.NUNOTA) 
	  WHERE I.CODPROD=ITE.CODPROD  AND CAB.TIPMOV = 'C' AND CAB.CODPARC NOT IN (6060,6055,6057,6064,6065,6056,6063,6061,6058,8570,6062))
ORDER BY PRO.CODPROD
