SELECT /*KARDEX - REAL*/
CONVERT(VARCHAR(10),CASE CAB.TIPMOV WHEN 'V' THEN CAB.DTNEG ELSE CAB.DTENTSAI END, 103) 'DATA',
PPR.DESCRPROD 'DESCRICAO',
PPR.COMPLDESC 'COMPLEMENTO',
PAR.NOMEPARC 'CLIENTE_FORNECEDOR',
CAB.NUNOTA 'NUMERO_UNICO',
CAB.NUMNOTA 'NOTA',
ITE.CODVOL,
CASE CAB.TIPMOV WHEN 'V' THEN 'VENDA' WHEN 'D' THEN 'DEVOLUCAO_VENDA' WHEN 'E' THEN 'DEVOLUCAO_COMPRA' WHEN 'T' THEN 'TRANSFERENCIA' ELSE 'COMPRA' END 'TIPO',
CASE CAB.TIPMOV WHEN 'V' THEN ITE.QTDNEG*-1 WHEN 'D' THEN ITE.QTDNEG WHEN 'E' THEN ITE.QTDNEG ELSE ITE.QTDNEG END 'QUANTIDADE',
CASE CAB.TIPMOV WHEN 'V' THEN ITE.VLRUNIT ELSE ITE.VLRUNIT END 'VALOR',

(SELECT ISNULL(SUM(I.ATUALESTOQUE * I.QTDNEG),0) FROM TGFITE I INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA) WHERE I.CODPROD=ITE.CODPROD AND I.ATUALESTOQUE <> 0 AND C.DTNEG < :PERIODO.INI AND C.CODEMP = CAB.CODEMP AND C.TIPMOV IN ('V','C','D','E','T')) +
SUM(ITE.QTDNEG*ITE.ATUALESTOQUE) OVER (PARTITION BY ITE.CODPROD ORDER BY ITE.CODPROD,CASE CAB.TIPMOV WHEN 'V' THEN CAB.DTNEG WHEN 'D' THEN CAB.DTNEG ELSE CAB.DTENTSAI END,CAB.NUNOTA) 'SALDO',
PPR.REFERENCIA 


FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TGFPRO PPR ON (PPR.CODPROD=ITE.CODPROD)
WHERE CAB.TIPMOV IN ('V','C','D','E','T')
AND CAB.STATUSNOTA IN ('L','A')
AND ITE.ATUALESTOQUE <> 0
AND PPR.REFERENCIA LIKE :PRODUTO
AND CAB.DTENTSAI BETWEEN :PERIODO.INI AND :PERIODO.FIN
/*AND (CAB.CODPARC = :CODPARC+'%' OR :CODPARC IS NULL)*/
AND CAB.CODEMP = :EMPRESA
ORDER BY ITE.CODPROD,CASE CAB.TIPMOV WHEN 'V' THEN CAB.DTNEG WHEN 'D' THEN CAB.DTNEG ELSE CAB.DTENTSAI END,CAB.NUNOTA