SELECT
CONVERT(VARCHAR(10),CASE TGFCAB.TIPMOV WHEN 'V' THEN TGFCAB.DTNEG ELSE TGFCAB.DTENTSAI END, 103) 'DATA',
PRO.DESCRPROD 'DESCRICAO',
PRO.COMPLDESC 'COMPLEMENTO',
P.NOMEPARC 'CLIENTE_FORNECEDOR',
TGFCAB.NUNOTA 'NUMERO_UNICO',
TGFCAB.NUMNOTA 'NOTA',
ITE.CODVOL,
CASE TGFCAB.TIPMOV WHEN 'V' THEN 'VENDA' WHEN 'D' THEN 'DEVOLUCAO_VENDA' WHEN 'E' THEN 'DEVOLUCAO_COMPRA' WHEN 'T' THEN 'TRANSFERENCIA' ELSE 'COMPRA' END 'TIPO',
CASE TGFCAB.TIPMOV WHEN 'V' THEN ITE.QTDNEG*-1 WHEN 'D' THEN ITE.QTDNEG WHEN 'E' THEN ITE.QTDNEG ELSE ITE.QTDNEG END 'QUANTIDADE',
CASE TGFCAB.TIPMOV WHEN 'V' THEN ITE.VLRUNIT ELSE ITE.VLRUNIT END 'VALOR',

(SELECT ISNULL(SUM(I.ATUALESTOQUE * I.QTDNEG),0) FROM TGFITE I INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA) WHERE I.CODPROD=ITE.CODPROD AND I.ATUALESTOQUE <> 0 AND C.DTENTSAI BETWEEN '2000-10-01' AND/*DTNEG <*/ :PERIODO.INI AND C.CODEMP = TGFCAB.CODEMP AND C.TIPMOV IN ('V','C','D','E','T')) +
SUM(ITE.QTDNEG*ITE.ATUALESTOQUE) OVER (PARTITION BY ITE.CODPROD ORDER BY ITE.CODPROD,CASE TGFCAB.TIPMOV WHEN 'V' THEN TGFCAB.DTNEG WHEN 'D' THEN TGFCAB.DTNEG ELSE TGFCAB.DTENTSAI END,TGFCAB.NUNOTA) 'SALDO',
PRO.REFERENCIA

FROM
  TGFCAB
  LEFT JOIN TGFVEN VEN ON (TGFCAB.CODVEND = VEN.CODVEND), TGFITE ITE INNER JOIN TGFPRO PRO ON (ITE.CODPROD=PRO.CODPROD), TGFPAR P, TGFTOP, TSIEMP EMP, TGFLOC LO
WHERE PRO.REFERENCIA LIKE :PRODUTO
AND (:EMPRESA = 0 OR ITE.CODEMP in (:EMPRESA, :EMPRESA))
AND ITE.ATUALESTOQUE <> 0
AND ITE.RESERVA = 'N'
AND TGFCAB.NUNOTA = ITE.NUNOTA
AND TGFCAB.DTENTSAI BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND TGFCAB.CODPARC = P.CODPARC
AND TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
AND ITE.CODEMP = EMP.CODEMP
AND ITE.CODLOCALORIG = LO.CODLOCAL

 AND ISNULL(TGFCAB.DTENTSAI,TGFCAB.DTNEG) >= :PERIODO.INI 
ORDER BY ISNULL(TGFCAB.DTENTSAI,TGFCAB.DTNEG) DESC, 11 ASC, ITE.ATUALESTOQUE DESC, TGFCAB.NUNOTA