SELECT /*LIBERAÇÃO DE PREÇO*/
	PRO.CODPROD, DE.CODEMP, PRO.REFERENCIA, PRO.DESCRPROD, LTRIM(RTRIM(PRO.UNIDADE)) AS 'UNIDADE',
	CASE WHEN DE.VLRDESC IN (0,0.01) THEN DE.VLRDESC WHEN DE.VLRDESC > 0.01 AND CODEMP<> 1 THEN DE.VLRDESC WHEN DE.VLRDESC > 0.01 THEN DE.VLRDESC END  AS 'PERC_DESC'
	,CASE WHEN DE.CODEMP IN (1,6,8,9,11) THEN SANKHYA.SNK_PRECO(0,PRO.CODPROD) WHEN DE.CODEMP IN (2,3,4,7,12) THEN SANKHYA.SNK_PRECO(1,PRO.CODPROD) WHEN DE.CODEMP IN (22) THEN SANKHYA.SNK_PRECO(100,PRO.CODPROD) END  AS 'VALOR_PRODUTO'
	,CASE WHEN DE.CODEMP IN (1,6,8,9,11) THEN (SANKHYA.SNK_PRECO(0,PRO.CODPROD)-(SANKHYA.SNK_PRECO(0,PRO.CODPROD)*CASE WHEN DE.CODEMP IN (1) THEN (ISNULL(DE.VLRDESC,1)/100) WHEN DE.CODEMP IN (6,8,9,11) AND DE.VLRDESC NOT IN (8.5,10.5) THEN (ISNULL(DE.VLRDESC,1)/100) WHEN DE.CODEMP IN (6,8,9,11) THEN (ISNULL(DE.VLRDESC+2,1)/100) END))
		 WHEN DE.CODEMP IN (2,3,4,7,12) THEN SANKHYA.SNK_PRECO(1,PRO.CODPROD)-(SANKHYA.SNK_PRECO(1,PRO.CODPROD)*CASE WHEN DE.CODEMP IN (2,3,4,7,12) AND DE.VLRDESC NOT IN (18.5,20.5) THEN (ISNULL(DE.VLRDESC,1)/100) WHEN DE.CODEMP IN (2,3,4,7,12) THEN (ISNULL(DE.VLRDESC+2,1)/100) END) 
		 WHEN DE.CODEMP IN (22) THEN SANKHYA.SNK_PRECO(100,PRO.CODPROD)-(SANKHYA.SNK_PRECO(100,PRO.CODPROD)*CASE WHEN DE.CODEMP IN (22) AND DE.VLRDESC NOT IN (18.5,20.5) THEN (ISNULL(DE.VLRDESC,1)/100) WHEN DE.CODEMP IN (22) THEN (ISNULL(DE.VLRDESC,1)/100) END) 
		 END  AS 'DESCONTO'
	, SANKHYA.SNK_PRECO(8,PRO.CODPROD) AS 'ESPECIAL'
	, SANKHYA.SNK_PRECO(2,PRO.CODPROD) AS 'AZUL'
	, SANKHYA.SNK_PRECO(5,PRO.CODPROD) AS 'VERDE'
	, SANKHYA.SNK_PRECO(6,PRO.CODPROD) AS 'VERMELHA'
	, ISNULL([sankhya].[SNK_GET_CUSTO]('ENTRADACOMICMS',PRO.CODPROD,DE.CODEMP,0,' ',GETDATE(),'S','N','N'),0) AS 'CUSTO_ATUAL'
	, ISNULL([sankhya].[SNK_GET_CUSTO]('ENTRADACOMICMS',PRO.CODPROD,DE.CODEMP,0,' ',GETDATE(),'S','N','N')*115/100,0) AS 'MVA15_CUSTO' 
       
FROM TGFPRO PRO LEFT JOIN AD_DESCEMP DE ON PRO.CODPROD = DE.CODPROD
WHERE PRO.CODPROD = ISNULL(:CODPROD,PRO.CODPROD)
ORDER BY PRO.REFERENCIA, DE.CODEMP


