SELECT DISTINCT * 
  FROM (
SELECT DISTINCT *
    FROM (

SELECT DISTINCT P.REFERENCIA, P.DESCRPROD, D. CODLOCATA AS 'ATACADO', D.CODLOCAVA AS 'VAREJO', E.ESTOQUE, B.CODBARRA
FROM TGFPRO P 
	INNER JOIN AD_LOCALEMP D ON (D.CODEMP = :CODEMP AND D.CODPROD = P.CODPROD)
	INNER JOIN TGFEST E ON (E.CODPROD = D.CODPROD AND E.CODEMP = :CODEMP AND E.ESTOQUE > 0)
	LEFT JOIN TGFBAR B ON (B.CODPROD=P.CODPROD)
WHERE P.USOPROD = 'R'
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND P.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND P.REFERENCIA LIKE :GRUPO+'%')
  ))
AND P.ATIVO = :ATIVO
AND (
	:LOCAL IS NULL OR :LOCAL IS NOT NULL AND (
	(D.CODLOCAVA LIKE :LOCAL+'%')
  ))
AND :TIPO = 'V'
--ORDER BY D.CODLOCAVA, P.REFERENCIA

UNION 

SELECT DISTINCT P.REFERENCIA, P.DESCRPROD, D.CODLOCATA AS 'ATACADO', D.CODLOCAVA AS 'VAREJO', E.ESTOQUE, B.CODBARRA
FROM TGFPRO P 
	INNER JOIN AD_LOCALEMP D ON (D.CODEMP = :CODEMP AND D.CODPROD = P.CODPROD)
	INNER JOIN TGFEST E ON (E.CODPROD = D.CODPROD AND E.CODEMP = :CODEMP AND E.ESTOQUE > 0)
	LEFT JOIN TGFBAR B ON (B.CODPROD=P.CODPROD)
WHERE P.USOPROD = 'R'
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND P.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND P.REFERENCIA LIKE :GRUPO+'%')
  ))
AND P.ATIVO = :ATIVO
AND (
	:LOCAL IS NULL OR :LOCAL IS NOT NULL AND (
	(D.CODLOCATA LIKE :LOCAL+'%')
  ))
AND :TIPO = 'A'

) SUB) X