SELECT PAR.CODPARC, PAR.RAZAOSOCIAL, FIN.DTVENC, FIN.NUMNOTA AS NOTA, FIN.NUFIN AS FINANCEIRO, FIN.NURENEG, CAB.DTENTSAI AS DATA_COMPRA, FIN.VLRDESDOB AS VALOR, datediff(DD, FIN.DTVENC, GETDATE()) as DIA_ATRASO
FROM TGFFIN FIN 
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = FIN.CODPARC)
INNER JOIN TGFCAB CAB ON (CAB.NUNOTA = FIN.NUNOTA)
WHERE FIN.DTVENC <= GETDATE()-2
AND FIN.DHBAIXA IS NULL
AND FIN.CODEMP = 1
AND CAB.TIPMOV = 'V'
AND FIN.CODTIPTIT <> 69
AND PAR.CLIENTE = 'S'
ORDER BY DIA_ATRASO DESC

--SELECT * FROM TGFCAB WHERE NUMNOTA = 423918
-- 45 BOLETO, 61 CARTEIRA, 57 CDL
--TAXADIAATRASO = 0,03, PERMULTA = 2
--SELECT * FROM TSIPAR WHERE CHAVE = 'TAXADIAATRASO'