SELECT /*PRODUTOS SEM DESCONTO*/
	PRO.CODPROD, DE.CODEMP, PRO.REFERENCIA, PRO.DESCRPROD
	,CASE WHEN DE.VLRDESC IN (0,0.01) THEN DE.VLRDESC WHEN DE.VLRDESC > 0.01 AND CODEMP<> 1 THEN DE.VLRDESC WHEN DE.VLRDESC > 0.01 THEN DE.VLRDESC END  AS 'PERC_DESC'
	,CASE WHEN DE.CODEMP IN (2,3,4,7,12) THEN SANKHYA.SNK_PRECO(1,PRO.CODPROD) WHEN DE.CODEMP IN (1,6,8,9,11) THEN SANKHYA.SNK_PRECO(0,PRO.CODPROD) END  AS 'VALOR_ATUAL'
	   
FROM TGFPRO PRO LEFT JOIN AD_DESCEMP DE ON (PRO.CODPROD = DE.CODPROD and de.CODEMP = :CODEMP)
WHERE DE.VLRDESC IN (0.01) 
AND SANKHYA.SNK_PRECO(0, de.CODPROD) > 0
AND PRO.ATIVO = 'S'
AND PRO.USOPROD = 'R'
AND pro.AD_PROREAL = 'S'
ORDER BY PRO.REFERENCIA, DE.CODEMP
