SELECT *

  FROM (
SELECT /*RELATORIO COMPRAS POR FORNECEDOR*/
    RANK() OVER (ORDER BY TOTAL_COMPRA_PRODUTO_AC DESC) AS RANK,
	COD_PARCEIRO,
	NOME_PARCEIRO,
	TOTAL_COMPRA_PRODUTO_AC AS 'COMPRAS-1',
	TOTAL_COMPRA_PRODUTO_AC1 AS 'COMPRAS-2',
	TOTAL_COMPRA_PRODUTO_AC2 AS 'COMPRAS-3'

FROM (

SELECT TOP 100 PERCENT
CAB.CODPARC COD_PARCEIRO,
PAR.NOMEPARC NOME_PARCEIRO,

ISNULL((SELECT
SUM(C.VLRNOTA) VLRTOT
FROM TGFCAB C
WHERE C.CODTIPOPER IN (701,712)
AND C.STATUSNOTA = 'L'
AND C.CODPARC=CAB.CODPARC
AND ((CONVERT(DATE,C.DTENTSAI) BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -2, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))))
),0) TOTAL_COMPRA_PRODUTO_AC

,ISNULL((SELECT
SUM(C.VLRNOTA) VLRTOT
FROM TGFCAB C
WHERE C.CODTIPOPER IN (701,712)
AND C.STATUSNOTA = 'L'
AND C.CODPARC=CAB.CODPARC
AND ((CONVERT(DATE,C.DTENTSAI) BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -3, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -2, GETDATE()))))
),0) TOTAL_COMPRA_PRODUTO_AC1

,ISNULL((SELECT
SUM(C.VLRNOTA) VLRTOT
FROM TGFCAB C
WHERE C.CODTIPOPER IN (701,712)
AND C.STATUSNOTA = 'L'
AND C.CODPARC=CAB.CODPARC
AND ((CONVERT(DATE,C.DTENTSAI) BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -4, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -3, GETDATE()))))
),0) TOTAL_COMPRA_PRODUTO_AC2

FROM TGFCAB CAB
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)

WHERE CAB.CODTIPOPER IN (700,712)
  AND CAB.STATUSNOTA = 'L'
  AND EMP.CODEMP = 1

AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
AND ((CONVERT(DATE,CAB.DTENTSAI) BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -4, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))))
GROUP BY  CAB.CODPARC, PAR.NOMEPARC
ORDER BY TOTAL_COMPRA_PRODUTO_AC DESC

) SUB
WHERE TOTAL_COMPRA_PRODUTO_AC > 0) X

ORDER BY 4 DESC