SELECT CODEMP,NOMEFANTASIA,MES,ANO,VLR_ESTOQUE ESTOQUE,VLR_COMPRAS COMPRAS,VLR_FATURAMENTO FATURAMENTO,
(VLR_FATURAMENTO/VLR_ESTOQUE) GIRO,
(VLR_ESTOQUE/VLR_FATURAMENTO) COBERTURA

FROM (

	SELECT SUB1.CODEMP,SUB1.NOMEFANTASIA,SUB1.MES,SUB1.ANO,SUM(SUB1.VLR_ESTOQUE) VLR_ESTOQUE,

	(
		ISNULL((SELECT SUM(I.VLRTOT)+SUM(I.VLRICMS)+SUM(I.VLRSUBST)-SUM(VLRDESC)+ 
		SUM(CASE WHEN C.VLRFRETE > 0 THEN 0 WHEN C.VLRFRETE > 0 THEN ((C.VLRFRETE)/C.VLRNOTA) END)
		FROM TGFITE I WITH (NOLOCK) INNER JOIN TGFCAB C WITH (NOLOCK) ON C.NUNOTA = I.NUNOTA
				WHERE C.STATUSNOTA = 'L' AND C.TIPMOV = 'C' AND C.CODEMP = SUB1.CODEMP
				AND YEAR(C.DTENTSAI) = SUB1.ANO AND MONTH(C.DTENTSAI) = SUB1.MES
				AND C.CODVEND <> 59 AND C.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
			),0) - ISNULL((SELECT SUM(I.VLRTOT)+SUM(I.VLRICMS)+SUM(I.VLRSUBST)-SUM(VLRDESC)+SUM(C.VLRFRETE) FROM TGFITE I WITH (NOLOCK) INNER JOIN TGFCAB C WITH (NOLOCK) ON C.NUNOTA = I.NUNOTA
				WHERE C.STATUSNOTA = 'L' AND C.TIPMOV = 'E' AND C.CODEMP = SUB1.CODEMP
				AND YEAR(C.DTENTSAI) = SUB1.ANO AND MONTH(C.DTENTSAI) = SUB1.MES
				AND C.CODVEND <> 59 AND C.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
			),0)
		) VLR_COMPRAS,
	/*(SELECT SUM(VLRNOTA) FROM TGFCAB WITH (NOLOCK)
		WHERE STATUSNOTA = 'L' AND TIPMOV = 'C' AND CODEMP = SUB1.CODEMP
		AND YEAR(DTENTSAI) = SUB1.ANO AND MONTH(DTENTSAI) = SUB1.MES
		AND CODVEND <> 59 AND NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
		) VLR_COMPRAS,*/

	(
		ISNULL((SELECT SUM(I.VLRTOT) FROM TGFITE I WITH (NOLOCK) INNER JOIN TGFCAB C WITH (NOLOCK) ON C.NUNOTA = I.NUNOTA
				WHERE C.STATUSNOTA = 'L' AND C.TIPMOV = 'V' AND C.CODEMP = SUB1.CODEMP
				AND YEAR(C.DTNEG) = SUB1.ANO AND MONTH(C.DTNEG) = SUB1.MES
				AND C.CODVEND <> 59 AND C.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
			),0) - ISNULL((SELECT SUM(I.VLRTOT) FROM TGFITE I WITH (NOLOCK) INNER JOIN TGFCAB C WITH (NOLOCK) ON C.NUNOTA = I.NUNOTA
				WHERE C.STATUSNOTA = 'L' AND C.TIPMOV = 'D' AND C.CODEMP = SUB1.CODEMP
				AND YEAR(C.DTNEG) = SUB1.ANO AND MONTH(C.DTNEG) = SUB1.MES
				AND C.CODVEND <> 59 AND C.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
			),0)
		) VLR_FATURAMENTO
	/*(SELECT SUM(VLRNOTA) FROM TGFCAB WITH (NOLOCK)
		WHERE STATUSNOTA = 'L' AND TIPMOV = 'V' AND CODEMP = SUB1.CODEMP
		AND YEAR(DTNEG) = SUB1.ANO AND MONTH(DTNEG) = SUB1.MES
		AND CODVEND <> 59 AND NUNOTA IN (SELECT NUNOTA FROM TGFFIN WITH (NOLOCK) WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)
		) VLR_FATURAMENTO*/

	FROM (

		SELECT EMP.CODEMP,EMP.NOMEFANTASIA,CTE.CODPROD,MONTH(CTE.DTCONTAGEM) MES,YEAR(CTE.DTCONTAGEM) ANO,

		(ISNULL((SELECT TOP 1 ENTRADACOMICMS FROM TGFCUS WITH (NOLOCK) WHERE ENTRADACOMICMS > 0 AND CODEMP = EMP.CODEMP AND CODPROD = PRO.CODPROD AND
				(
					YEAR(DTATUAL) = YEAR(CTE.DTCONTAGEM) AND MONTH(DTATUAL) <= MONTH(CTE.DTCONTAGEM) OR
					YEAR(DTATUAL) < YEAR(CTE.DTCONTAGEM)
				)
			ORDER BY DTATUAL DESC),0)
			*
			ISNULL((SELECT TOP 1 QTDEST FROM TGFCTE WITH (NOLOCK) WHERE CODEMP = EMP.CODEMP AND CODPROD = PRO.CODPROD
				AND YEAR(DTCONTAGEM) = YEAR(CTE.DTCONTAGEM) AND MONTH(DTCONTAGEM) = MONTH(CTE.DTCONTAGEM)
			ORDER BY DTCONTAGEM DESC),0)
		) VLR_ESTOQUE



		FROM TSIEMP EMP WITH (NOLOCK)
		INNER JOIN TGFCTE CTE WITH (NOLOCK) ON CTE.CODEMP = EMP.CODEMP
		INNER JOIN TGFPRO PRO WITH (NOLOCK) ON PRO.CODPROD = CTE.CODPROD
		WHERE EMP.CODEMPMATRIZ = 1 AND EMP.CODEMP <> 5 AND PRO.ATIVO = 'S' AND PRO.USOPROD = 'R' --AND PRO.CODPROD=23967
		AND YEAR(CTE.DTCONTAGEM) = 2018
		GROUP BY EMP.CODEMP,EMP.NOMEFANTASIA,CTE.CODPROD,MONTH(CTE.DTCONTAGEM),YEAR(CTE.DTCONTAGEM),PRO.CODPROD

	) SUB1
	GROUP BY CODEMP,NOMEFANTASIA,MES,ANO

) SUB2

GROUP BY CODEMP,NOMEFANTASIA,MES,ANO,VLR_ESTOQUE,VLR_COMPRAS,VLR_FATURAMENTO
ORDER BY CODEMP,MES

--SELECT * FROM TGFITE
--SELECT * FROM TGFCAB