SELECT /* INFORME FUNCIONARIOS*/ * 
  FROM (
SELECT *
    FROM (

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND R.DOMFER > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'E'
)


UNION ALL

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND R.ATRASOS > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL 

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.FALTAS <> 0
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND F.DTDEM IS NULL 
AND :TIPO = 'F'
)

UNION ALL 

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.AFASTAMENTO <> 0
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND F.DTDEM IS NULL
AND :TIPO = 'X'
)

UNION ALL

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.LICENCA <> 0
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND F.DTDEM IS NULL
AND :TIPO = 'L'
)

UNION ALL

(SELECT DISTINCT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, 
	CAST (R.FALTAS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.FALTAS - ((R.FALTAS / 60) * 60) AS VARCHAR),2) AS FALTAS,
	CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60 AS VARCHAR) + ':' 
		+ RIGHT('0'+CAST ((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) 
		- (((R.DOMFERNOT + R.EXTRANOT + R.EXCEDENTE + R.DOMFER + R.EXTRA) / 60) * 60) AS VARCHAR),2) AS EXTRA,
	CAST ((R.EXCEDENTENOT + R.NOTURNA) / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST ((R.EXCEDENTENOT + R.NOTURNA) - (((R.EXCEDENTENOT + R.NOTURNA) / 60) * 60) AS VARCHAR),2) AS NOTURNA,
	CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS AFASTAMENTO,
	CAST (R.LICENCA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.LICENCA - ((R.LICENCA / 60) * 60) AS VARCHAR),2) AS LICENCA,
	CAST (R.BONIFICADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.BONIFICADO - ((R.BONIFICADO / 60) * 60) AS VARCHAR),2) AS BONIFICADO,
	O.DESCROCOR,
	H.DESCRHISTOCOR
FROM TSIEMP E INNER JOIN TFPFUN F ON (E.CODEMP = F.CODEMP)
		INNER JOIN TFPRPO R ON (F.CODFUNC = R.CODFUNC AND F.CODEMP = R.CODEMP)
		LEFT JOIN TFPOCO O ON (F.CODFUNC = O.CODFUNC AND F.CODEMP=R.CODEMP AND O.CODHISTOCOR IN (29,22,18,19) AND CONVERT(date, R.DTALTER) = CONVERT(date, O.DTALTER))
		LEFT JOIN TFPHIS H ON (O.CODHISTOCOR=H.CODHISTOCOR)
		INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.BONIFICADO <> 0
AND (
		(USU.CODEMP IS NULL AND R.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND R.CODEMP = USU.CODEMP)
	)
AND (
		(USU.CODEMP IS NULL AND F.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND F.CODEMP = USU.CODEMP)
	)
AND F.DTDEM IS NULL
AND :TIPO = 'B'
)

) SUB) X