WITH X AS (
SELECT 
    VEN.APELIDO AS 'VENDEDOR'
	 , CAB.CODEMP
	 , MONTH (CAB.DTNEG) AS 'MES'
	 , YEAR (CAB.DTNEG) AS 'ANO'
	 , SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN 'S' = 'N' THEN VGF.INDITENS ELSE 1 END) AS 'VALOR'
    
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TGFVEN VEN ON (VEN.CODVEND=CAB.CODVEND)
INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
 LEFT JOIN VGFCAB VGF ON (CAB.NUNOTA=VGF.NUNOTA)
WHERE (CAB.CODEMP = 22)
--AND CONVERT(DATE,CAB.DTNEG) BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -6, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -5, GETDATE()))
AND CAB.DTNEG BETWEEN '01/01/2019' and '30/06/2020'
AND CAB.CODTIPOPER IN (900,901,931,934,935,936,937)
AND CAB.TIPMOV='V'
AND CAB.STATUSNOTA = 'L'
--AND CAB.CODVEND NOT IN (0,59)

--AND (
--	('S' = 'S' AND ((CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER <> 931))
--	OR 'S' = 'N'
--	))
GROUP BY CAB.DTNEG, CAB.CODEMP, VEN.APELIDO) --Select * from X

SELECT VENDEDOR,CODEMP, MES, ANO
	 , format(ROUND(CONVERT(MONEY,VALOR),2),'##,##0.00') AS 'VALOR'

  FROM (SELECT VENDEDOR AS 'VENDEDOR'
			,CODEMP
			, MES
			, ANO
			 , SUM(VALOR) AS 'VALOR'

		  FROM X
		 GROUP BY CODEMP, MES, ANO, VENDEDOR) Z
order by CODEMP,ANO Asc, MES , VENDEDOR
