SELECT /*RELACAO DE MATERIAIS*/
* FROM (

	SELECT
		(SELECT LTRIM(RTRIM(NOMEFANTASIA)) FROM TSIEMP WHERE CODEMP = 4) AS EMPRESA

	  --, SUBSTRING(PRO.REFERENCIA, 1, 4) AS GRUPO

	  , SUBSTRING(PRO.REFERENCIA, 5, LEN(PRO.REFERENCIA)) AS CODIGO

	  , PRO.REFERENCIA AS REFERENCIA

	  , PRO.DESCRPROD AS DESCRICAO
	  , EMP.CODLOCATA AS ATACADO
	  , EMP.CODLOCAVA AS VAREJO

	  , ISNULL((SELECT SUM(I.QTDNEG*I.ATUALESTOQUE)
			FROM TGFITE I
			INNER JOIN TGFCAB C ON (C.NUNOTA = I.NUNOTA)
			WHERE I.CODPROD = PRO.CODPROD AND I.CODEMP = 4 AND I.ATUALESTOQUE <> 0 AND I.QTDNEG <> 0 AND I.RESERVA = 'N' AND C.DTENTSAI <= '10/12/2018'
		),0) AS QTDE_ESTOQUE

	  , ISNULL((SELECT MAX(I.QTDNEG) FROM TGFCAB C
			INNER JOIN TGFITE I ON (I.NUNOTA=C.NUNOTA)
			WHERE I.CODPROD = PRO.CODPROD
			AND C.NUNOTA = (SELECT MAX(CA.NUNOTA) FROM TGFCAB CA
				INNER JOIN TGFITE IT ON (IT.NUNOTA=CA.NUNOTA)
				WHERE IT.CODPROD = PRO.CODPROD
				AND CA.TIPMOV = 'C'
				AND CA.DTMOV <= '10/12/2018'
				AND IT.CODEMP = 4)
		),0) AS QTDE_COMPRADA

		
	FROM TGFPRO PRO
	LEFT OUTER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD AND EST.CODEMP = 4)
	LEFT OUTER JOIN AD_LOCALEMP EMP ON (EMP.CODPROD = PRO.CODPROD AND EST.CODEMP = EMP.CODEMP)
	WHERE ((SUBSTRING(ISNULL(PRO.REFERENCIA,'123'),1,3) = SUBSTRING(ISNULL('202','123'),1,3)) OR '202' IS NULL) AND EST.ESTOQUE >0

) SUB
WHERE QTDE_COMPRADA > 0
ORDER BY
    CAST(SUBSTRING(ISNULL(REFERENCIA,'000'), 1, 3) AS INT) ASC,
    LEN(REFERENCIA) ASC,
    REFERENCIA ASC


