SELECT /* INFORME FUNCIONARIOS*/ * 
  FROM (
SELECT *
    FROM (

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN	'25/06/2019' AND '14/07/2019'
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.DOMFER > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'E'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN	'25/06/2019' AND '14/07/2019'
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.EXTRA > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'E'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN	'25/06/2019' AND '14/07/2019'
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.EXCEDENTE > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'E'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.ATRASOS > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.NOTURNA > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.EXTRANOT > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.CODEMP = :CODEMP
AND R.EXCEDENTENOT > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC in :CODFUNC
AND R.CODEMP = :CODEMP
AND R.DOMFERNOT > 0
AND F.DTDEM IS NULL 
AND :TIPO = 'A'
)

UNION ALL 

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.FALTAS <> 0
AND R.CODEMP = :CODEMP
AND F.DTDEM IS NULL 
AND :TIPO = 'F'
)

UNION ALL 

(SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME, R.DTMOV, R.APONTAMENTOS, R.FALTAS, 
CAST (R.ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATRASOS - ((R.ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
CAST (R.EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRA - ((R.EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
CAST (R.EXCEDENTE / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXCEDENTE - ((R.EXCEDENTE / 60) * 60) AS VARCHAR),2) AS EXCEDENTE,
CAST (R.DOMFER / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFER - ((R.DOMFER / 60) * 60) AS VARCHAR),2) AS DOMFER,
CAST (R.NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.NOTURNA - ((R.NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA,
CAST (R.EXTRANOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.EXTRANOT - ((R.EXTRANOT / 60) * 60) AS VARCHAR),2) AS EXTRANOT,
CAST (R.DOMFERNOT / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.DOMFERNOT - ((R.DOMFERNOT / 60) * 60) AS VARCHAR),2) AS DOMFERNOT,
CAST (R.ATESTADO / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (R.ATESTADO - ((R.ATESTADO / 60) * 60) AS VARCHAR),2) AS ATESTADO
FROM TFPRPO R LEFT JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
	LEFT JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE R.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND R.CODFUNC IN :CODFUNC
AND R.AFASTAMENTO <> 0
AND R.CODEMP = :CODEMP
AND F.DTDEM IS NULL
AND :TIPO = 'X'
)

) SUB) X