SELECT DISTINCT P.REFERENCIA,P.CODPROD 'CODIGO', P.DESCRPROD AS 'DESCRICAO', 

(SELECT AVG(ISNULL((ITE.VLRTOT),0)/ISNULL((ITE.QTDNEG),0))  AS 'MEDIA_MES_ANTERIOR'
FROM TGFITE ITE INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
				INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND ITE.CODEMP = :EMPRESA
AND P.CODPROD = PRO.CODPROD
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
  ))
AND CAB.CODTIPOPER NOT IN (909,912,903,915,924,922,913,920)
AND CAB.CODTIPOPER IN (900)
AND CAB.DTENTSAI BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -2, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
) AS 'MEDIA_MES_ANTERIOR',

(SELECT AVG(ISNULL((ITE.VLRTOT),0)/ISNULL((ITE.QTDNEG),0)) AS 'MEDIA_PERIODO'
FROM TGFITE ITE INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
				INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND ITE.CODEMP = :EMPRESA
AND P.CODPROD=ITE.CODPROD
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
  ))
AND CAB.CODTIPOPER NOT IN (909,912,903,915,924,922,913,920)
AND CAB.CODTIPOPER IN (900)
AND CAB.DTENTSAI BETWEEN :PERIODO.INI AND :PERIODO.FIN
) AS 'MEDIA_PERIODO',

(SELECT AVG(ISNULL((ITE.VLRTOT),0)/ISNULL((ITE.QTDNEG),0)) AS 'TRIMESTRE'
FROM TGFITE ITE INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
				INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND ITE.CODEMP = :EMPRESA
AND P.CODPROD=ITE.CODPROD
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
  ))
AND CAB.CODTIPOPER NOT IN (909,912,903,915,924,922,913,920)
AND CAB.CODTIPOPER IN (900)
AND CAB.DTENTSAI BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -4, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
) AS 'TRIMESTRE' ,

(SELECT AVG(ISNULL((ITE.VLRTOT),0)/ISNULL((ITE.QTDNEG),0)) AS 'SEMESTRE'
FROM TGFITE ITE INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
				INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
WHERE CAB.TIPMOV='V'
AND CAB.STATUSNFE = 'A'
AND ITE.CODEMP = :EMPRESA
AND P.CODPROD=ITE.CODPROD
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
  ))
AND CAB.CODTIPOPER NOT IN (909,912,903,915,924,922,913,920)
AND CAB.CODTIPOPER IN (900)
AND CAB.DTENTSAI BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -7, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
) AS 'SEMESTRE'

FROM TGFPRO P INNER JOIN TGFITE I ON (P.CODPROD=I.CODPROD)
			  INNER JOIN TGFCAB C ON (I.NUNOTA=C.NUNOTA)
WHERE I.CODEMP = :EMPRESA
AND C.TIPMOV='V'
AND C.STATUSNFE = 'A'
AND C.CODTIPOPER NOT IN (909,912,903,915,924,922,913,920)
AND C.CODTIPOPER IN (900)
AND C.DTENTSAI BETWEEN DATEADD(DAY,1,EOMONTH(DATEADD(MONTH, -7, GETDATE()))) AND EOMONTH(DATEADD(MONTH, -1, GETDATE()))
AND (
	:GRUPO IS NULL OR :GRUPO IS NOT NULL AND (
	(LEN(:GRUPO) > 4 AND P.REFERENCIA LIKE :GRUPO) OR
	(LEN(:GRUPO) <= 4 AND P.REFERENCIA LIKE :GRUPO+'%')
  ))
ORDER BY P.REFERENCIA