WITH W AS (
SELECT NUMNOTA
     , NUNOTA
     , DTNEG
	 , RAZAOSOCIAL
	 , CODVEND
	 , SUM(VLRVENDA) AS PRECOTABELA
	 , SUM(VLRTOT) AS VLRTOT
	 , SUM(DESCONTO) AS DESCONTO
	 , SUM(ACRESCIMO) AS ACRESCIMO
	 , (1-(SUM(VLRTOT)/CASE WHEN SUM(VLRVENDA) = 0 THEN SUM(VLRTOT) ELSE SUM(VLRVENDA) END))*-100 AS PERC
	 , STUFF((
            SELECT DISTINCT ',' + N.NOMETAB
            FROM TGFNTA N INNER JOIN TGFTAB T ON N.CODTAB = T.CODTAB
			              INNER JOIN TGFITE I ON T.NUTAB = I.NUTAB
					WHERE I.NUNOTA = X.NUNOTA
            FOR XML PATH('')
            ), 1, 1, '') AS TABELAS
  FROM (
SELECT CAB.NUMNOTA
     , CAB.DTNEG
     , CAB.NUNOTA
	 , PAR.RAZAOSOCIAL
	 , CAB.CODVEND
	 , CAB.VLRNOTA
	 , ITE.VLRTOT AS VLRTOT
	 , [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG AS VLRVENDA
	 , CASE WHEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG > ITE.VLRTOT THEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG - ITE.VLRTOT ELSE 0 END AS DESCONTO
	 , CASE WHEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG <= ITE.VLRTOT THEN ITE.VLRTOT - [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG  ELSE 0 END AS ACRESCIMO
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TGFVEN VEN ON (VEN.CODVEND=CAB.CODVEND)
INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
 LEFT JOIN TGFTAB TAB ON ITE.NUTAB = TAB.NUTAB
WHERE CAB.CODPARC = ISNULL(17335,CAB.CODPARC)
--AND
--(
--		(USU.CODEMP IS NULL AND CAB.CODEMP IN (12)) OR
--		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
--	)
AND 
CAB.DTNEG BETWEEN '01/11/2018' AND '30/11/2018'
AND CAB.CODTIPOPER IN (900,901)
AND CAB.TIPMOV='V'
AND CAB.STATUSNOTA = 'L'
--AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
AND (
	('S' = 'S' AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69))
	OR 'S' = 'N'
)
AND 1 = 1
UNION ALL
SELECT NULL AS NUMNOTA
     , NULL AS DTNEG
     , NULL AS NUNOTA
	 , VEN.APELIDO AS RAZAOSOCIAL
	 , CAB.CODVEND
	 , CAB.VLRNOTA
	 , ITE.VLRTOT AS VLRTOT
	 , [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG AS VLRVENDA
	 , CASE WHEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG > ITE.VLRTOT THEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG - ITE.VLRTOT  ELSE 0 END AS DESCONTO
	 , CASE WHEN [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG <= ITE.VLRTOT THEN ITE.VLRTOT - [sankhya].[AD_PRECO](ITE.NUTAB,ITE.CODPROD,CAB.DTNEG)*ITE.QTDNEG  ELSE 0 END AS ACRESCIMO
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TGFVEN VEN ON (VEN.CODVEND=CAB.CODVEND)
INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
 LEFT JOIN TGFTAB TAB ON ITE.NUTAB = TAB.NUTAB
WHERE CAB.CODPARC = ISNULL(17335,CAB.CODPARC)
AND
(
		(USU.CODEMP IS NULL AND CAB.CODEMP IN (12)) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)
AND 
CAB.DTNEG BETWEEN '01/11/2018' AND '30/11/2018'
AND CAB.CODTIPOPER IN (900,901)
AND CAB.TIPMOV='V'
AND CAB.STATUSNOTA = 'L'
--AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
AND (
	('S' = 'S' AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69))
	OR 'S' = 'N'
)
AND 2 = 1
) X
GROUP BY NUMNOTA
     , NUNOTA
     , DTNEG
	 , RAZAOSOCIAL
	 , CODVEND
)


SELECT * 
     , (SELECT (1-(SUM(PRECOTABELA)/CASE WHEN SUM(VLRTOT) = 0 THEN SUM(PRECOTABELA) ELSE SUM(VLRTOT) END)) FROM W)*100 AS PERC_TOTAL
	 , (SELECT (1-(SUM(VLRTOT)/CASE WHEN SUM(PRECOTABELA) = 0 THEN SUM(VLRTOT) ELSE SUM(PRECOTABELA) END)) FROM W)*100 AS PERC_TOTAL1
  FROM W
 WHERE ((PERC > 0 AND 'D' = 'A')
    OR (PERC < 0 AND 'D' = 'D')
    OR (PERC = 0 AND 'D' = 'S')
    OR ('D' = 'T'))
ORDER BY 1