SELECT /*LANÇAMENTOS PEDIDOS*/
DISTINCT EMP.CODEMP, EMP.NOMEFANTASIA, COUNT(ITE.CODPROD) AS 'ITENS', 
(SELECT DISTINCT COUNT (C.NUNOTA) 
FROM TGFCAB C
	INNER JOIN TSIUSU U ON (U.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
	INNER JOIN TSIEMP E ON (E.CODEMP=C.CODEMP)
WHERE C.CODUSU = :CODUSU
	AND C.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
	AND C.TIPMOV = 'O'
	AND C.CODTIPOPER NOT IN (100)
	AND C.STATUSNOTA = CAB.STATUSNOTA
	AND (C.CODEMP = CAB.CODEMP)
	AND (CAB.CODEMP IS NULL OR CAB.CODEMP IN :CODEMP)
) AS 'PEDIDO',
SUM(ITE.VLRTOT) AS 'VALOR',
(SELECT DISTINCT SUM (I.QTDNEG) 
FROM TGFCAB C
	INNER JOIN TGFITE I ON (C.NUNOTA = I.NUNOTA)
	INNER JOIN TSIUSU U ON (U.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
	INNER JOIN TSIEMP E ON (E.CODEMP=C.CODEMP)
WHERE C.CODUSU = :CODUSU
	AND C.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
	AND C.TIPMOV = 'O'
	AND C.CODTIPOPER NOT IN (100)
	AND C.STATUSNOTA = CAB.STATUSNOTA
	AND (C.CODEMP = CAB.CODEMP)
	AND (CAB.CODEMP IS NULL OR CAB.CODEMP IN :CODEMP)
) AS 'QUANTIDADE',
SUM(ITE.VLRTOT) AS 'VALOR',
CASE WHEN CAB.STATUSNOTA = 'L' THEN 'LIBERADO' ELSE 'NÃO LIBERADO' END AS 'STATUS'

FROM TGFCAB CAB 
	INNER JOIN TGFITE ITE ON (CAB.NUNOTA=ITE.NUNOTA)
	INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
	INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
WHERE CAB.CODUSU = :CODUSU
AND CAB.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CAB.TIPMOV = 'O'
AND CAB.CODTIPOPER NOT IN (100)
AND (CAB.CODEMP IS NULL OR CAB.CODEMP IN :CODEMP)
GROUP BY EMP.CODEMP,EMP.NOMEFANTASIA,CAB.STATUSNOTA, CAB.CODEMP,CAB.STATUSNOTA