SELECT

(SELECT LTRIM(RTRIM(NOMEFANTASIA)) FROM TSIEMP WHERE CODEMP = $P{P_CODEMP}) AS EMPRESA,
LTRIM(RTRIM(TIT.DESCRTIPTIT))  As "DescTipTitulo",
CASE T.TIPMOV
	WHEN 'I' THEN 'Fin.'
	WHEN 'G' THEN 'Pag.'
	WHEN 'R' THEN 'Rec.'
	WHEN 'V' THEN 'Venda'
	WHEN 'C' THEN 'Compra'
	WHEN 'O' THEN 'Ped.Compra'
	WHEN 'P' THEN 'Ped.Venda'
	WHEN 'D' THEN 'Devolucao'
	ELSE 'Outros'
END As "Tipo_de_Movimento",

CASE T.TIPMOV WHEN 'D' THEN (FIN.VLRDESDOB) ELSE 0 END As soma_devolucoes,
CASE T.TIPMOV WHEN 'D' THEN (FIN.VLRDESDOB*-1) ELSE FIN.VLRDESDOB END As soma_total,
((CASE T.TIPMOV WHEN 'D' THEN (FIN.VLRDESDOB) ELSE FIN.VLRDESDOB END)-(CASE T.TIPMOV WHEN 'D' THEN (FIN.VLRDESDOB) ELSE 0 END)) As total,

CASE CAB.STATUSNFE
	WHEN 'A' THEN 'APROVADO'
	WHEN 'E' THEN 'AGUARDANDO AUTORIZAÇÃO'
	WHEN 'I' THEN 'CONTIGENCIA'
	ELSE 'Outros'
END As "SITUACAO",

FIN.NUMNOTA As "Nro_Nota",
FIN.DTNEG As "DtNegoc",
FIN.CODPARC As "CodParceiro",
LTRIM(RTRIM(PAR.RAZAOSOCIAL))  As "Razao_Social_do_Parceiro",
FIN.VLRDESDOB As "Vlr_Desdob",
LTRIM(RTRIM(USU.NOMEUSU))  As "Usuario_Caixa"

FROM TGFFIN FIN , TGFTOP T , TGFPAR PAR , TGFTIT TIT , TGFCAB CAB , TSIUSU USU

WHERE FIN.CODPARC = PAR.CODPARC
AND CAB.CODUSU = USU.CODUSU
AND FIN.CODTIPOPER = T.CODTIPOPER
AND FIN.NUMNOTA = CAB.NUMNOTA
AND TIT.CODTIPTIT <> 62 AND TIT.CODTIPTIT = FIN.CODTIPTIT
AND FIN.DHTIPOPER = T.DHALTER

AND (
	( CASE WHEN FIN.PROVISAO = 'S' THEN 'Sim' ELSE 'Não' END <> 'Sim')
	AND  FIN.CODEMP = $P{P_CODEMP}
	AND  FIN.DTNEG = $P{P_DATA}
	AND  FIN.CODTIPOPER IN (900,901, 1000, 1001, 1002,1007)
)

AND (( CASE WHEN FIN.RECDESP <> 0 THEN 'Sim' ELSE 'Não' END = 'Sim'))


ORDER BY "DescTipTítulo", "Tipo_de_Movimento"