SELECT VEN.CODVEND, FUN.NOMEFUNC, SUM(CAB.VLRNOTA) AS TOTAL
from TGFCAB CAB
INNER JOIN TGFVEN VEN ON (VEN.CODVEND=CAB.CODVEND)
INNER JOIN TFPFUN FUN ON (VEN.CODFUNC=FUN.CODFUNC)
WHERE CAB.DTNEG BETWEEN '01/02/2018' AND '28/02/2018'
AND VEN.CODEMP=1
AND CAB.TIPMOV = 'V'
AND CAB.STATUSNFE IN ('A')
GROUP BY VEN.CODVEND, FUN.NOMEFUNC
