SELECT /*ULTIMAS ENTRADAS*/
* FROM (
	SELECT row_number() OVER (ORDER BY PRODUTO ASC,DATA_ENTRADA DESC,NUNOTA DESC) AS row_number, *
	FROM (

		SELECT
			RTRIM(LTRIM(PAR.NOMEPARC)) AS 'FORN',
			CAB.DTENTSAI AS 'DATA_ENTRADA',
			PRO.REFERENCIA AS 'PRODUTO',
			PRO.DESCRPROD AS 'DESCRICAO',
			CAB.NUMNOTA AS 'NF',
			CAB.NUNOTA AS 'NUNOTA',
			ITE.QTDNEG AS 'QTDE',
			ITE.VLRUNIT AS 'V_UNIT',
			CASE WHEN Cab.VLRFRETE > 0 THEN((((((ITE.VLRTOT)*100)/(SELECT SUM(I.VLRTOT) FROM TGFITE I WHERE I.NUNOTA=CAB.NUNOTA)/100)*Cab.VLRFRETE)/ITE.QTDNEG)) END  AS 'FRETE',
			/*CASE WHEN CAB.VLRFRETE = 0 THEN 0 WHEN CAB.VLRFRETE > 0 THEN ((CAB.VLRFRETE*100)/CAB.VLRNOTA) END AS 'PERC_FRETE',*/
			ALIQIPI AS 'IPI',
			ISNULL((SELECT DISTINCT (VALOR/ITE.QTDNEG) FROM TGFDIN WHERE NUNOTA=ITE.NUNOTA AND CODIMP = 6 AND SEQUENCIA=ITE.SEQUENCIA),0)+
			ISNULL((SELECT DISTINCT (VALOR/ITE.QTDNEG) FROM TGFDIN WHERE NUNOTA=ITE.NUNOTA AND CODIMP = 7 AND SEQUENCIA=ITE.SEQUENCIA),0) AS 'PISCOFINS',
			CASE WHEN ITE.VLRSUBST = 0 THEN 0 WHEN ITE.VLRSUBST >0 THEN (ITE.VLRSUBST/ITE.QTDNEG) END  AS 'ST',
			ISNULL((SELECT DISTINCT (AD_DIFST/ITE.QTDNEG) FROM TGFDIN WHERE NUNOTA=ITE.NUNOTA AND CODIMP=2 AND SEQUENCIA=ITE.SEQUENCIA),0)  AS 'DIF_ST',
			CASE WHEN (CAB.VLRDESTAQUE+CAB.VLRSEG+CAB.VLROUTROS) = 0 THEN 0 ELSE (((((ITE.VLRUNIT*ITE.QTDNEG)*100)/(SELECT SUM(VLRUNIT*QTDNEG) FROM TGFITE WHERE NUNOTA = CAB.NUNOTA))/100)*(CAB.VLRDESTAQUE+CAB.VLRSEG+CAB.VLROUTROS))/ITE.QTDNEG END AS VLROUTROS,
			CASE WHEN CAB.VLRFRETE > 0 THEN (ITE.VLRUNIT+((ITE.VLRUNIT+ITE.VLRIPI/ITE.QTDNEG)*(((((((ITE.VLRTOT))/(SELECT SUM(I.VLRTOT) FROM TGFITE I WHERE I.NUNOTA=CAB.NUNOTA)/100)*Cab.VLRFRETE)/ITE.QTDNEG))))+ITE.VLRUNIT*(ALIQIPI*0.01))
			WHEN (ITE.VLRUNIT+((ITE.VLRUNIT+ITE.VLRUNIT*(ALIQIPI*0.01)))+ITE.VLRUNIT*(ALIQIPI*0.01)) > 0 THEN (ITE.VLRUNIT+ITE.VLRUNIT*(ALIQIPI*0.01))
			ELSE ITE.VLRUNIT END + CASE WHEN (CAB.VLRDESTAQUE+CAB.VLRSEG+CAB.VLROUTROS) = 0 THEN 0 ELSE (((((ITE.VLRUNIT*ITE.QTDNEG)*100)/(SELECT SUM(VLRUNIT*QTDNEG) FROM TGFITE WHERE NUNOTA = CAB.NUNOTA))/100)*(CAB.VLRDESTAQUE+CAB.VLRSEG+CAB.VLROUTROS))/ITE.QTDNEG END AS 'VALOR_TOTAL'
			

		FROM TGFCAB CAB
		INNER JOIN TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
		INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
		INNER JOIN TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)

		WHERE CAB.TIPMOV = 'C'
		AND CAB.STATUSNOTA = 'L'
		AND CAB.CODEMP = :EMPRESA
		AND (
			(LEN(:GRUPO) > 4 AND PRO.REFERENCIA LIKE :GRUPO) OR
			(LEN(:GRUPO) <= 4 AND PRO.REFERENCIA LIKE :GRUPO+'%')
		)
		AND (
			(:GERENCIAL = 'S' AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR :GERENCIAL = 'N'
		)

	) SUB
) TabelaNumerada
WHERE row_number BETWEEN 0 AND 100

