SELECT
CAB.CODEMP,
LTRIM(RTRIM(EMP.NOMEFANTASIA)) EMPRESA,
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.DTNEG,
LTRIM(RTRIM(PAR.RAZAOSOCIAL)) CLIENTE,
USU.NOMEUSU USUARIO,
CAB.VLRNOTA

FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
LEFT OUTER JOIN TSIUSU USU ON (USU.CODUSU = CAB.CODUSU)

WHERE CAB.TIPMOV = 'C'
AND CAB.CODTIPOPER IN (712,701)
AND CAB.DTNEG >= '01/12/2017' AND CAB.DTNEG < CONVERT(CHAR(10),GETDATE(),103)
AND (CAB.STATUSNOTA IS NULL OR CAB.STATUSNOTA NOT IN ('A','L'))
ORDER BY CAB.DTNEG,CAB.NUNOTA