SELECT DISTINCT

C1.CODEMP,
C1.PENDENTE,
C1.NUNOTA ORIGEM,
P1.NOMEPARC NOME_ORIGEM,
C1.DTNEG DATA_ORIGEM,
C2.NUNOTA DESTINO,
C2.PENDENTE PENDENTE2,
P2.NOMEPARC NOME_DESTINO,
C2.DTNEG DATA_DESTINO

FROM TGFVAR V
INNER JOIN TGFCAB C1 ON C1.NUNOTA = V.NUNOTAORIG
INNER JOIN TGFCAB C2 ON C2.NUNOTA = V.NUNOTA
INNER JOIN TGFPAR P1 ON P1.CODPARC = C1.CODPARC
INNER JOIN TGFPAR P2 ON P2.CODPARC = C1.CODPARC

WHERE C1.DTNEG > C2.DTNEG