SELECT
	CODIGO,
	LOJA,
	COD_FUN,
	NOME,
	FALTAS,
	CAST (ATRASOS / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (ATRASOS - ((ATRASOS / 60) * 60) AS VARCHAR),2) AS ATRASOS,
	--ATRASOS,
	CAST (EXTRA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (EXTRA - ((EXTRA / 60) * 60) AS VARCHAR),2) AS EXTRA,
	--EXTRA,
	CAST (NOTURNA / 60 AS VARCHAR) + ':' + RIGHT('0'+CAST (NOTURNA - ((NOTURNA / 60) * 60) AS VARCHAR),2) AS NOTURNA
	--NOTURNA

FROM (

SELECT F.CODEMP CODIGO,
E.NOMEFANTASIA LOJA,
F.CODFUNC COD_FUN,
F.NOMEFUNC NOME,

(SELECT COUNT(FALTAS)
FROM TFPRPO
WHERE DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CODFUNC = F.CODFUNC
AND FALTAS <> 0
) FALTAS,

(SELECT SUM(ATRASOS) ATRASO
FROM TFPRPO
WHERE DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CODFUNC = F.CODFUNC
) ATRASOS,

(SELECT SUM(EXTRA+EXCEDENTE+DOMFER)
FROM TFPRPO
WHERE DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CODFUNC = F.CODFUNC
) EXTRA,

(SELECT SUM(NOTURNA+EXTRANOT+EXCEDENTENOT+DOMFERNOT)
FROM TFPRPO
WHERE DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND CODFUNC = F.CODFUNC
) NOTURNA


FROM TFPRPO R
INNER JOIN TFPFUN F ON (F.CODFUNC = R.CODFUNC)
INNER JOIN TSIEMP E ON (E.CODEMP = F.CODEMP)
WHERE F.CODEMP IN :CODEMP
AND F.CODFUNC IN :CODFUNC

GROUP BY F.CODEMP, F.CODFUNC, F.NOMEFUNC, E.NOMEFANTASIA
--ORDER BY F.CODEMP, F.CODFUNC

) SUB