SELECT /*TOTAL VENDAS POR VENDEDOR*/
EMP.CODEMP CODEMP, EMP.NOMEFANTASIA EMPRESA, VEN.CODVEND,
VEN.APELIDO VENDEDOR, SUM(ITE.VLRTOT) TOTAL_VENDAS
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON (CAB.NUNOTA=ITE.NUNOTA)
INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
INNER JOIN TGFTPV TPV ON (TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA)
INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND=VEN.CODVEND)
WHERE CAB.CODTIPOPER IN (900, 901)
AND CAB.TIPMOV = 'V'
AND (('S' = 'S' AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69))
OR 'S' = 'N')
AND DATEADD(DAY, 0, CAB.DTENTSAI) >= CAST(DATEADD(day, 0, GETDATE()) as DATE)
--AND CAB.DTENTSAI BETWEEN '20/08/2018' AND '20/08/2018'
GROUP BY EMP.CODEMP, EMP.NOMEFANTASIA, VEN.APELIDO, VEN.CODVEND
ORDER BY EMP.CODEMP, VEN.APELIDO