SELECT * FROM (

--  VENDAS POR LOJA
/* VENDAS POR LOJA */

SELECT
    LEN(REFERENCIA) AS TAMANHONOME,
    EMP.NOMEFANTASIA,
    ITE.CODPROD,
    PRO.DESCRPROD,
    PRO.REFERENCIA,
    SUM(ITE.ATUALESTOQUE * -1 * ITE.QTDNEG) AS QTDNEG,
    SUM(ITE.ATUALESTOQUE * -1 * ITE.VLRTOT) AS VLRUNT,
    -- ISNULL(MIN(EST.ESTOQUE),0) AS ESTOQUE,
(SELECT ISNULL(SUM(I.ATUALESTOQUE * I.QTDNEG),0) FROM TGFITE I INNER JOIN TGFCAB C ON (C.NUNOTA=I.NUNOTA) WHERE I.CODPROD=ITE.CODPROD AND I.ATUALESTOQUE <> 0 AND C.DTENTSAI <= $P{DTFIM} AND C.CODEMP = CAB.CODEMP AND C.TIPMOV IN ('V','C','D','E')) AS ESTOQUE,
(SELECT SUM(ISNULL(QTDNEG-QTDENTREGUE,0)) FROM TGFITE INNER JOIN TGFCAB ON TGFCAB.NUNOTA = TGFITE.NUNOTA AND ITE.CODPROD = TGFITE.CODPROD WHERE TGFCAB.TIPMOV = 'O' AND TGFCAB.PENDENTE = 'S' AND TGFITE.PENDENTE = 'S' AND TGFCAB.STATUSNOTA = 'L' AND TGFCAB.CODEMP = $P{CODEMP} ) AS PEDIDO
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
INNER JOIN TGFTPV TPV ON (TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA)
LEFT JOIN TGFEST EST ON (EST.CODPROD = ITE.CODPROD AND EST.CODEMP = ITE.CODEMP AND EST.ESTOQUE<=0)
WHERE (CAB.CODTIPOPER IN (900,901, 1000,1001, 1007) AND TPV.SUBTIPOVENDA IN (1,7,8,2,3,5))
AND ((SUBSTRING(ISNULL(REFERENCIA,'123'),1,3) = SUBSTRING(ISNULL($P{REFERENCIA},'123'),1,3)) OR $P{REFERENCIA} IS NULL)
AND ($P{CODEMP} = CAB.CODEMP OR $P{CODEMP} IS NULL)
AND (CAB.DTNEG >= $P{DTINI} AND CAB.DTNEG <= $P{DTFIM})
AND (CAB.TIPMOV IN  (
                    CASE WHEN $P{VENDA} = 'true' THEN 'V' END,
                    CASE WHEN $P{DEVOLUCAO} = 'true' THEN 'D' END,
                    CASE WHEN $P{TRANSFERENCIA} = 'true' THEN 'T' END
                    ))
AND CAB.STATUSNOTA = 'L'
AND (
	($P{GERENCIAL} = 'S' AND CAB.CODVEND <> 59 AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69))
	OR $P{GERENCIAL} = 'N'
)
GROUP BY
    EMP.NOMEFANTASIA,
    ITE.CODPROD,
    PRO.DESCRPROD,
    PRO.REFERENCIA,
    CAB.CODEMP
) SUB
ORDER BY
    CAST(SUBSTRING(REFERENCIA, 1, 3) AS INT),
    TAMANHONOME,
    REFERENCIA