CREATE TRIGGER AD_TRG_INC_DESCONTO

ON TGFPRO 

FOR INSERT 
AS
BEGIN 
	DECLARE
		@CODPROD INT,
		@USOPROD CHAR(1),
		@AD_CODPAULISTA VARCHAR(10)

	SELECT 
		@CODPROD = CODPROD,
		@USOPROD = USOPROD,
		@AD_CODPAULISTA = AD_CODPAULISTA
	FROM 
		INSERTED
	
	IF (@USOPROD = 'R' AND @AD_CODPAULISTA IS NULL)
	BEGIN
	
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,1,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC)  
		VALUES (@CODPROD,2,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,3,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,4,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,6,	0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,7,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,8,	0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,9,	0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,11,0.01)

		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,12,0.01)
		
		Print 'Desconto Inserido 0.01"'
		
	RETURN
	END
	ELSE IF(@USOPROD = 'R' AND @AD_CODPAULISTA ='S')
	BEGIN
	
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) 
		VALUES (@CODPROD,22,0.01)

		Print 'Desconto Inserido 0.01"'
				
	RETURN
	END

END