CREATE TRIGGER AD_TRG_INC_DESCONTO

ON TGFPRO 

AFTER INSERT
AS
BEGIN 
DECLARE
	@CODPROD INT,
	@USOPROD CHAR(1),
	@REFERENCIA VARCHAR(30),
	@AD_CODPAULISTA VARCHAR(10)

	SELECT 
		@CODPROD = CODPROD,
		@USOPROD = USOPROD,
		@AD_CODPAULISTA = AD_CODPAULISTA,
		@REFERENCIA = REFERENCIA

	FROM INSERTED
	
	IF (@USOPROD = 'R' AND @AD_CODPAULISTA IS NULL)
	BEGIN
	
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,1,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,2,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,3,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,4,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,6,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,7,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,8,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,9,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,11,0.01)
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,12,0.01)
		
		Print 'Desconto Inserido 0.01'

		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,1,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,2,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,3,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,4,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,6,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,7,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,8,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,9,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,11,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')
		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,12,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')

		Print 'LOCALIZAÇÃO INSERIDA SEM LOCAÇIZAÇÃO'

		INSERT INTO TGFBAR(CODBARRA,CODPROD,DHALTER,CODUSU,CODVOL) VALUES(replace(replace(@REFERENCIA,'.',''),'-','')+'0001',@CODPROD,'01/01/2019',0,'PC')

		Print 'CODIGO DE BARRAS'
		
	RETURN
	END
	ELSE IF(@USOPROD = 'R' AND @AD_CODPAULISTA ='S')
	BEGIN
	
		INSERT INTO AD_DESCEMP (CODPROD, CODEMP, VLRDESC) VALUES (@CODPROD,22,0.01)

		Print 'Desconto Inserido 0.01'

		INSERT INTO AD_LOCALEMP(CODPROD,CODEMP,CODLOCATA,CODLOCAVA) VALUES(@CODPROD,22,'SEM LOCALIZAÇÃO','SEM LOCALIZAÇÃO')

		Print 'LOCALIZAÇÃO INSERIDA SEM LOCAÇIZAÇÃO'
				
	RETURN
	END

END