WHILE((SELECT MIN(TPV.CODTIPTIT) FROM TGFTIT TPV WHERE CODTIPTIT NOT IN (
select P.CODTIPTIT from AD_CTAEMP T INNER JOIN TGFTIT P ON (T.CODTIPTIT=P.CODTIPTIT)
where T.CODEMP = 14)) <= 
(SELECT MAX(TPV.CODTIPTIT) FROM TGFTIT TPV WHERE CODTIPTIT NOT IN (
select P.CODTIPTIT from AD_CTAEMP T INNER JOIN TGFTIT P ON (T.CODTIPTIT=P.CODTIPTIT)
where T.CODEMP = 14))
)
BEGIN

INSERT INTO AD_CTAEMP ( CODCTABCOINT,CODEMP,CODTIPTIT ) VALUES (
400,14,
(SELECT MIN(TPV.CODTIPTIT) FROM TGFTIT TPV WHERE CODTIPTIT NOT IN (
select P.CODTIPTIT from AD_CTAEMP T INNER JOIN TGFTIT P ON (T.CODTIPTIT=P.CODTIPTIT)
where T.CODEMP = 14)))

END
