SELECT /*PRODUTOS MAIS VENDIDOS*/
* FROM (
    SELECT row_number() OVER (ORDER BY SUM(ITE.VLRTOT) DESC) AS row_number,
    PRD.DESCRPROD PRODUTO,
    SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN :GERENCIAL = 'N' THEN VGF.INDITENS ELSE 1 END) TOTAL_VENDAS
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON (ITE.NUNOTA=CAB.NUNOTA)
INNER JOIN TGFPAR PAR ON (PAR.CODPARC=CAB.CODPARC)
INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
INNER JOIN TSICID CID ON (CID.CODCID=PAR.CODCID)
INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
INNER JOIN VGFCAB VGF ON CAB.NUNOTA = VGF.NUNOTA
WHERE /*AND (
		(USU.CODEMP IS NULL AND CAB.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)*/
CAB.CODEMP IN :CODEMP
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
AND CAB.CODTIPOPER IN (900,901,931,934,935)
AND CAB.STATUSNOTA = 'L'
AND CAB.TIPMOV='V'
AND (
	(:GERENCIAL = 'S' AND ((CAB.CODVEND <> 59 AND CAB.CODPARC NOT IN (7441) AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER NOT IN (934,931,912) AND CAB.CODPARC NOT IN (7441)))
		OR :GERENCIAL = 'N'
	))
GROUP BY PRD.DESCRPROD
HAVING SUM(ITE.VLRTOT)>0
) TabelaNumerada
WHERE row_number <= 15