SELECT /*TOTAL DE VENDAS*/
 CODEMP,
	EMPRESA,
	SUM(A_VISTA) A_VISTA,
	SUM(A_PRAZO) A_PRAZO,
	SUM(TOTAL_VENDA) TOTAL_VENDA,
	SUM(DEVOLUCAO) DEVOLUCAO,
	SUM(TOTAL_VENDA)+SUM(DEVOLUCAO) RESULTADO
FROM (

    SELECT
		 EMP.CODEMP CODEMP,
        EMP.NOMEFANTASIA EMPRESA,
        SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN :GERENCIAL = 'N' THEN VGF.INDITENS ELSE 1 END) A_VISTA,
        0 A_PRAZO,
        0 TOTAL_VENDA,
        0 DEVOLUCAO
    FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON (CAB.NUNOTA=ITE.NUNOTA)
    INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
	INNER JOIN TGFTPV TPV ON (TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA)
    INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
	INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
     LEFT JOIN VGFCAB VGF ON CAB.NUNOTA = VGF.NUNOTA
    WHERE CAB.CODTIPOPER IN (900,901,931,934,935)
    AND TPV.SUBTIPOVENDA IN (1,7,8)
	AND CAB.STATUSNOTA = 'L'
    AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
    /*AND (
		(USU.CODEMP IS NULL AND CAB.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)*/
	AND CAB.CODEMP IN :CODEMP
    AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
	AND (
		(:GERENCIAL = 'S' AND ((CAB.CODVEND <> 59 AND CAB.CODPARC NOT IN (7441) AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER NOT IN (934,931,912) AND CAB.CODPARC NOT IN (7441)))
		OR :GERENCIAL = 'N'
	))
    GROUP BY EMP.NOMEFANTASIA, EMP.CODEMP

    UNION ALL

    SELECT
		 EMP.CODEMP CODEMP,
        EMP.NOMEFANTASIA EMPRESA,
        0 A_VISTA,
        SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN :GERENCIAL = 'N' THEN VGF.INDITENS ELSE 1 END) A_PRAZO,
        0 TOTAL_VENDA,
        0 DEVOLUCAO
    FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON (CAB.NUNOTA=ITE.NUNOTA)
    INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
	INNER JOIN TGFTPV TPV ON (TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA)
    INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
	INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
     LEFT JOIN VGFCAB VGF ON CAB.NUNOTA = VGF.NUNOTA
    WHERE CAB.CODTIPOPER IN (900,901,931,934,935)
    AND TPV.SUBTIPOVENDA IN (2,3,5)
	AND CAB.STATUSNOTA = 'L'
    AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
    /*AND (
		(USU.CODEMP IS NULL AND CAB.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)*/
	AND CAB.CODEMP IN :CODEMP
    AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
	AND (
		(:GERENCIAL = 'S' AND ((CAB.CODVEND <> 59 AND CAB.CODPARC NOT IN (7441) AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER NOT IN (934,931,912) AND CAB.CODPARC NOT IN (7441)))
		OR :GERENCIAL = 'N'
	))
    GROUP BY EMP.NOMEFANTASIA, EMP.CODEMP

    UNION ALL

    SELECT
		 EMP.CODEMP CODEMP,
        EMP.NOMEFANTASIA EMPRESA,
        0 A_VISTA,
        0 A_PRAZO,
        SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN :GERENCIAL = 'N' THEN VGF.INDITENS ELSE 1 END)TOTAL_VENDA,
        0 DEVOLUCAO
    FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON (CAB.NUNOTA=ITE.NUNOTA)
    INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
	INNER JOIN TGFTPV TPV ON (TPV.CODTIPVENDA=CAB.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA)
    INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
	INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
     LEFT JOIN VGFCAB VGF ON CAB.NUNOTA = VGF.NUNOTA
    WHERE CAB.CODTIPOPER IN (900,901,931,934,935)
    AND TPV.SUBTIPOVENDA IN (1,7,8,2,3,5)
	AND CAB.STATUSNOTA = 'L'
    AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
    /*AND (
		(USU.CODEMP IS NULL AND CAB.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)*/
	AND CAB.CODEMP IN :CODEMP
    AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
	AND (
		(:GERENCIAL = 'S' AND ((CAB.CODVEND <> 59 AND CAB.CODPARC NOT IN (7441) AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER NOT IN (934,931,912) AND CAB.CODPARC NOT IN (7441)))
		OR :GERENCIAL = 'N'
	))
    GROUP BY EMP.NOMEFANTASIA, EMP.CODEMP

    UNION ALL

    SELECT
		 EMP.CODEMP CODEMP,
        EMP.NOMEFANTASIA EMPRESA,
        0 A_VISTA,
        0 A_PRAZO,
        0 TOTAL_VENDA,
        SUM((ITE.VLRTOT-ITE.VLRDESC)*CASE WHEN :GERENCIAL = 'N' THEN VGF.INDITENS ELSE 1 END)*-1 DEVOLUCAO
    FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON (CAB.NUNOTA=ITE.NUNOTA)
    INNER JOIN TSIEMP EMP ON (EMP.CODEMP=CAB.CODEMP)
    INNER JOIN TGFPRO PRD ON (PRD.CODPROD=ITE.CODPROD)
	INNER JOIN TSIUSU USU ON (USU.CODUSU=SANKHYA.STP_GET_CODUSULOGADO())
     LEFT JOIN VGFCAB VGF ON CAB.NUNOTA = VGF.NUNOTA
    WHERE CAB.CODTIPOPER IN (1000,1001,1007,1009,792,1011,1012)
	AND CAB.STATUSNOTA = 'L'
    AND CAB.DTMOV BETWEEN :PERIODO.INI AND :PERIODO.FIN
    /*AND (
		(USU.CODEMP IS NULL AND CAB.CODEMP IN :CODEMP) OR
		(USU.CODEMP IS NOT NULL AND CAB.CODEMP = USU.CODEMP)
	)*/
	AND CAB.CODEMP IN :CODEMP
    AND (PRD.REFERENCIA LIKE :REFERENCIA+'%' OR :REFERENCIA IS NULL)
	AND (
		(:GERENCIAL = 'S' AND ((CAB.CODVEND <> 59 AND CAB.CODPARC NOT IN (7441) AND CAB.NUNOTA IN (SELECT NUNOTA FROM TGFFIN WHERE ORIGEM = 'E' AND CODTIPTIT <> 69)) OR (CAB.CODTIPOPER NOT IN (934,931,912) AND CAB.CODPARC NOT IN (7441)))
		OR :GERENCIAL = 'N'
	))
    GROUP BY EMP.NOMEFANTASIA, EMP.CODEMP

) SUB
GROUP BY EMPRESA, CODEMP
ORDER BY CODEMP
--ORDER BY TOTAL_VENDA DESC